// constants/cosmetics.ts
import { Option, StudioPreset } from '../types';
import { 
    CameraIcon, CosmeticsIcon,
    TopDownAngleIcon, FortyFiveDegreeAngleIcon, EyeLevelAngleIcon,
    ExtremeCloseUpAngleIcon,
    DeepDofIcon, SelectiveFocusIcon, ShallowDofIcon,
    StudioLightIcon, HardLightIcon, BacklightIcon, NaturalWindowLightIcon,
} from '../components/icons';

const COSMETICS_CAMERAS: Option[] = [
    { name: "Canon R5 + 100mm Macro (Cores Vivas)", short_info: "Ciência de cores renomada para fidelidade.", keywords: ["canon R5", "color accuracy", "dynamic range", "studio cosmetics", "45MP sensor profile", "true-to-life color"], icon: CameraIcon, technical_details: { title: "Canon R5: A Mestra das Cores", description: "Famosa por sua fidelidade de cor, esta opção é perfeita para capturar o tom real de batons, sombras e bases. Garante que o vermelho do batom seja o vermelho verdadeiro do produto.", pro_tips: ["Excelente para fotografar 'swatches' de produtos contra fundos brancos puros para e-commerce.", "A lente RF 100mm Macro revela a textura de pós e a cremosidade de produtos líquidos."] } },
    { name: "Sony a7R V + 90mm Macro (Detalhe Extremo)", short_info: "Resolução e nitidez máximas para publicidade.", keywords: ["sony a7r V", "61 megapixels", "g master macro", "extreme sharpness", "commercial advertising", "liquid detail", "ultimate resolution"], icon: CameraIcon, technical_details: { title: "Sony a7R V: A Lupa Digital", description: "O auge da resolução. O sensor de 61MP, combinado com uma lente macro G Master, captura detalhes surreais. É a escolha para publicidade de alto nível, onde cada partícula de brilho e a textura do produto precisam ser perfeitas.", pro_tips: ["Ideal para grandes impressões ou outdoors.", "O autofoco com IA ajuda a travar o foco precisamente no detalhe desejado.", "Revela texturas em líquidos e cremes de forma impressionante."] } },
    { name: "Fuji GFX 100 II + 120mm Macro (Look de Luxo)", short_info: "Qualidade de médio formato para campanhas.", keywords: ["fujifilm gfx 100 ii", "medium format", "102mp", "luxury cosmetics", "editorial look", "unmatched detail", "deep color tones"], icon: CameraIcon, technical_details: { title: "Fuji GFX 100 II: O Padrão do Luxo", description: "Um sistema de médio formato que define o padrão para fotografia de luxo. O sensor maior produz imagens com uma profundidade tridimensional e riqueza de cores ideais para marcas de cosméticos de alta gama.", pro_tips: ["Ideal para campanhas publicitárias e editoriais de revistas de beleza.", "As cores são ricas e profundas, perfeitas para embalagens sofisticadas e texturas de produtos."] } },
    { name: "iPhone 15 Pro (Look de Celular)", short_info: "Fotografia computacional para redes sociais.", keywords: ["iphone 15 pro", "computational photography", "hdr", "social media look", "sharp and punchy", "macro mode", "e-commerce ready"], icon: CameraIcon, technical_details: { title: "iPhone 15 Pro: O Look das Redes Sociais", description: "Utiliza IA para criar imagens prontas para as redes sociais: nítidas, vibrantes e com HDR impressionante. O modo macro é surpreendentemente capaz de capturar detalhes em texturas de maquiagem para posts rápidos.", pro_tips: ["Excelente para criar conteúdo rápido e de alta qualidade para Instagram ou TikTok.", "As cores são otimizadas para telas, fazendo os produtos se destacarem."] } },
];
const COSMETICS_DEPTHS_OF_FIELD: Option[] = [
    { name: "Focus Stacking (Nitidez Total)", short_info: "Todo o produto em nitidez perfeita.", keywords: ["focus stacking", "fully sharp", "deep focus cosmetics", "macro sharp", "aperture f/16", "edge-to-edge sharpness"], icon: DeepDofIcon, technical_details: { title: "Focus Stacking: O Padrão Profissional", description: "Simula a técnica profissional onde múltiplas fotos com diferentes pontos de foco são combinadas para criar uma imagem final onde o produto inteiro, do ponto mais próximo ao mais distante, está perfeitamente nítido.", pro_tips: ["Essencial para frascos de perfume e embalagens com texto.", "Garante que cada detalhe do produto seja visível e claro para e-commerce."] } },
    { name: "Foco Seletivo (f/2.8)", short_info: "Destaca um detalhe (logo, textura).", keywords: ["selective macro focus", "shallow dof", "texture focus", "detail isolation", "aperture f/2.8", "bokeh"], icon: SelectiveFocusIcon, technical_details: { title: "Foco Seletivo (f/2.8): O Destaque Artístico", description: "Usa uma profundidade de campo rasa (abertura f/2.8) para focar em um único ponto de interesse, como o logo na embalagem ou a textura de um creme, deixando o resto em um desfoque suave.", pro_tips: ["Cria imagens de alto impacto para campanhas e redes sociais.", "Ideal para destacar a característica mais importante de um produto."] } },
    { name: "Bokeh Suave (f/4)", short_info: "Look suave e limpo, bom para skincare.", keywords: ["soft focus", "dreamy look", "ethereal cosmetics", "skincare photography", "aperture f/4", "natural bokeh background"], icon: ShallowDofIcon, technical_details: { title: "Bokeh Suave (f/4): O Toque Delicado", description: "Um desfoque de fundo suave (abertura f/4) que cria uma atmosfera delicada e limpa. Perfeito para produtos de skincare, transmitindo uma sensação de leveza e pureza.", pro_tips: ["Perfeito para produtos com uma estética mais orgânica e suave.", "Funciona bem com iluminação difusa para um look ainda mais delicado."] } },
    { name: "Foco Profundo (f/16)", short_info: "Nitidez de ponta a ponta para catálogos.", keywords: ["deep depth of field", "edge-to-edge sharpness", "aperture f/16", "f/22", "e-commerce", "product isolation"], icon: DeepDofIcon, technical_details: { title: "Foco Profundo (f/16): Clareza para Catálogo", description: "Utiliza uma profundidade de campo muito grande (abertura pequena como f/16) para garantir que grande parte do produto e do seu entorno próximo esteja nítido.", pro_tips: ["Bom para fotos de catálogo e lojas online onde o contexto importa.", "Requer mais luz, ideal para configurações de estúdio com flash."] } },
];
const COSMETICS_LIGHTING_STYLES: Option[] = [
    { name: "Luz de Estúdio (Softbox Triplo)", short_info: "Iluminação limpa, padrão para e-commerce.", keywords: ["three-point lighting", "clean cosmetics lighting", "studio shot", "no harsh reflections", "catalog product"], icon: StudioLightIcon, technical_details: { title: "Luz de Estúdio (Softbox Triplo): O Padrão para E-commerce", description: "A configuração clássica para fotografia de produtos. Usa três fontes de luz suave (softboxes) para iluminar a peça de maneira uniforme, eliminando sombras fortes e destacando a forma do produto.", pro_tips: ["Essencial para fotografar embalagens reflexivas.", "Cria um look profissional e limpo, ideal para fundos brancos."] } },
    { name: "Luz Dura (Brilho Intenso)", short_info: "Sombras nítidas para destacar texturas.", keywords: ["hard light", "specular highlights", "texture sparkle", "defined shadows", "direct flash"], icon: HardLightIcon, technical_details: { title: "Luz Dura: O Brilho das Texturas", description: "Vem de uma fonte de luz pequena e sem difusão, criando sombras de bordas nítidas e realces especulares (brilhos) intensos. É uma escolha ousada que pode realçar drasticamente a textura de pós ou o brilho de um gloss.", pro_tips: ["Use para criar um look dramático e de alto contraste.", "As sombras podem ser usadas como um elemento de composição forte."] } },
    { name: "Contraluz (Brilho no Produto)", short_info: "Luz por trás que faz líquidos brilharem.", keywords: ["backlight", "rim light", "halo effect", "liquid glow", "transparency"], icon: BacklightIcon, technical_details: { title: "Contraluz: O Brilho do Produto", description: "A luz principal vem de trás do produto, passando através de frascos translúcidos e criando um brilho interno. Também cria um contorno luminoso (rim light).", pro_tips: ["Ideal para perfumes e séruns para mostrar a clareza e o brilho do líquido.", "Use um pequeno rebatedor na frente para adicionar detalhe à parte frontal.", "Cria um look mágico e etéreo."] } },
    { name: "Luz de Janela (Natural)", short_info: "Luz suave para um estilo de vida orgânico.", keywords: ["natural window light", "soft diffused light", "organic feel", "lifestyle cosmetics shot", "daylight"], icon: NaturalWindowLightIcon, technical_details: { title: "Luz de Janela: A Beleza da Simplicidade", description: "A luz suave e difusa que entra por uma janela grande. É perfeita para criar um look de estilo de vida natural, orgânico e autêntico, mostrando o produto em um ambiente real.", pro_tips: ["Funciona melhor em dias nublados para uma luz ainda mais suave.", "Posicione o produto perto da janela para aproveitar ao máximo a luz e criar sombras suaves."] } },
];
const COSMETICS_CAMERA_ANGLES: Option[] = [
    { name: "Ângulo 45° (Hero Shot)", short_info: "O 'hero shot' versátil e natural.", keywords: ["hero shot", "three-quarter view", "natural perspective", "product photography", "depth perception"], icon: FortyFiveDegreeAngleIcon, technical_details: { title: "Ângulo 45° (Hero Shot): O Padrão Ouro", description: "O ângulo mais comum e eficaz para produtos. Mostra a frente e o lado da peça simultaneamente, oferecendo uma visão tridimensional que revela profundidade e forma.", pro_tips: ["A escolha ideal para a foto principal do produto.", "Funciona para quase todos os tipos de cosméticos."] } },
    { name: "De Cima (Flat Lay)", short_info: "Para paletas, pós e composições.", keywords: ["flat lay", "overhead shot", "catalog cosmetics", "composition", "clean layout"], icon: TopDownAngleIcon, technical_details: { title: "De Cima (Flat Lay): A Composição Completa", description: "Perfeito para exibir o design de itens que ficam planos, como paletas de sombra. Também é o ângulo padrão para 'flat lays' com outros objetos.", pro_tips: ["Use para criar 'moodboards' com os produtos, flores e outros adereços.", "A iluminação deve ser uniforme para evitar sombras indesejadas."] } },
    { name: "Frontal (Nível do Olhar)", short_info: "Mostra frascos e embalagens de frente.", keywords: ["eye-level shot", "head-on view", "direct perspective", "catalog clarity"], icon: EyeLevelAngleIcon, technical_details: { title: "Frontal (Nível do Olhar): A Visão Direta", description: "O ângulo clássico para frascos, mostrando o produto de frente. Faz o produto parecer imponente e foca no seu design principal, sendo ideal para fotos de catálogo.", pro_tips: ["Combine com Focus Stacking para nitidez total de frente.", "Ideal para mostrar a marca e o rótulo de forma clara."] } },
    { name: "Super Close-up (Macro)", short_info: "Foco em texturas de maquiagem e detalhes.", keywords: ["macro detail", "close-up shot", "makeup texture", "product swatch", "lipstick tip"], icon: ExtremeCloseUpAngleIcon, technical_details: { title: "Super Close-up (Macro): A Arte da Textura", description: "Um enquadramento super fechado que revela a textura de um batom, a cremosidade de uma base ou as partículas de brilho em uma sombra. É sobre mostrar a qualidade do produto.", pro_tips: ["Requer uma lente macro e iluminação precisa.", "Revela detalhes que não são visíveis a olho nu, agregando valor ao produto."] } },
];
const COSMETICS_PRESETS: StudioPreset[] = [
    { name: "Skincare (Minimalista)", description: "Cena limpa e fresca para produtos de skincare.", icon: CosmeticsIcon, preset: { cameraName: 'Canon R5 + 100mm Macro (Cores Vivas)', depthOfFieldName: 'Bokeh Suave (f/4)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'De Cima (Flat Lay)', stylePlaceholder: 'Frasco de sérum em uma superfície de mármore branco, com uma folha de costela-de-adão e gotas de água, fundo minimalista e claro.' }, examples: ["serum", "moisturizer", "face cream", "clean beauty", "minimalist", "water drops"] },
    { name: "Maquiagem (Vibrante)", description: "Realça as cores e texturas de maquiagens.", icon: CosmeticsIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro (Detalhe Extremo)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz Dura (Brilho Intenso)', angle: 'Super Close-up (Macro)', stylePlaceholder: 'Close-up extremo de uma paleta de sombras coloridas com pinceladas de textura, sobre um fundo de acrílico holográfico.' }, examples: ["eyeshadow palette", "lipstick swatch", "gloss", "foundation", "vibrant colors", "texture macro"] },
    { name: "Perfume (Luxo)", description: "Cena sofisticada e dramática para fragrâncias.", icon: CosmeticsIcon, preset: { cameraName: 'Fuji GFX 100 II + 120mm Macro (Look de Luxo)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Contraluz (Brilho no Produto)', angle: 'Frontal (Nível do Olhar)', stylePlaceholder: 'Frasco de perfume de luxo sobre uma mesa de vidro, com o líquido brilhando em contraluz e um fundo de tecido de seda escuro e amassado.' }, examples: ["perfume bottle", "fragrance", "luxury", "dramatic lighting", "silk background"] },
    { name: "Batom (Close-up Textura)", description: "Close-up extremo para mostrar a cor e textura de batons.", icon: CosmeticsIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro (Detalhe Extremo)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz Dura (Brilho Intenso)', angle: 'Super Close-up (Macro)', stylePlaceholder: 'Close-up da ponta de um batom vermelho cremoso, com pequenas gotas de água, sobre um fundo preto texturizado.' }, examples: ["lipstick", "lipstick texture", "macro beauty", "red lipstick", "creamy texture"] },
    { name: "Base & Corretivo (Pele)", description: "Mostra a textura e a cobertura de bases e corretivos.", icon: CosmeticsIcon, preset: { cameraName: 'Canon R5 + 100mm Macro (Cores Vivas)', depthOfFieldName: 'Bokeh Suave (f/4)', lightingName: 'Luz de Janela (Natural)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Frasco de base ao lado de uma pincelada do produto em uma superfície de vidro, com luz natural suave de uma janela.' }, examples: ["foundation", "concealer", "skin texture", "makeup swatch", "natural light"] },
    { name: "Esmalte (Unhas)", description: "Foco no frasco e na cor aplicada nas unhas.", icon: CosmeticsIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro (Detalhe Extremo)', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'Super Close-up (Macro)', stylePlaceholder: 'Close-up de unhas perfeitamente pintadas com esmalte brilhante, segurando o frasco do produto, com fundo limpo.' }, examples: ["nail polish", "manicure", "nail art", "nail color", "shiny nails"] },
    { name: "Produtos Masculinos", description: "Cena sofisticada para produtos de cuidados masculinos.", icon: CosmeticsIcon, preset: { cameraName: 'Fuji GFX 100 II + 120mm Macro (Look de Luxo)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz Dramática (Estilo Rembrandt)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Frasco de óleo de barba em uma bancada de madeira escura, ao lado de uma navalha vintage e um pente, com iluminação dramática.' }, examples: ["men\'s grooming", "beard oil", "shaving cream", "masculine", "dark mood"] },
    { name: "Orgânico & Natural", description: "Cena com elementos da natureza para produtos orgânicos.", icon: CosmeticsIcon, preset: { cameraName: 'Canon R5 + 100mm Macro (Cores Vivas)', depthOfFieldName: 'Bokeh Suave (f/4)', lightingName: 'Luz de Janela (Natural)', angle: 'De Cima (Flat Lay)', stylePlaceholder: 'Pote de creme facial orgânico cercado por folhas verdes frescas e pedras de rio, sobre uma superfície de ardósia molhada.' }, examples: ["organic cosmetics", "natural beauty", "skincare", "green leaves", "clean"] },
    { name: "Embalagem de Luxo", description: "Destaque para o design e os detalhes da embalagem.", icon: CosmeticsIcon, preset: { cameraName: 'Fuji GFX 100 II + 120mm Macro (Look de Luxo)', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'Frontal (Nível do Olhar)', stylePlaceholder: 'Caixa de produto de luxo com detalhes em relevo dourado, parcialmente aberta para revelar o frasco, sobre um fundo de seda.' }, examples: ["luxury packaging", "unboxing", "product box", "high-end", "gold details"] },
    { name: "Swatches de Textura", description: "Mostra as texturas e cores de vários produtos.", icon: CosmeticsIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro (Detalhe Extremo)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz Dura (Brilho Intenso)', angle: 'De Cima (Flat Lay)', stylePlaceholder: 'Pinceladas artísticas de base, sombra e batom em uma superfície de acrílico transparente, mostrando as diferentes texturas.' }, examples: ["makeup swatches", "texture shot", "smear", "product texture", "artistic makeup"] },
    { name: "Cuidados com o Cabelo", description: "Cena limpa e profissional para produtos de cabelo.", icon: CosmeticsIcon, preset: { cameraName: 'Canon R5 + 100mm Macro (Cores Vivas)', depthOfFieldName: 'Bokeh Suave (f/4)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Frascos de shampoo e condicionador em uma prateleira de banheiro moderna, com uma toalha branca enrolada e um fundo de azulejos limpos.' }, examples: ["haircare", "shampoo", "conditioner", "hair oil", "clean bathroom"] },
    { name: "E-commerce (Fundo Branco)", description: "Foto de produto clássica para lojas online.", icon: CosmeticsIcon, preset: { cameraName: 'Canon R5 + 100mm Macro (Cores Vivas)', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'Frontal (Nível do Olhar)', stylePlaceholder: 'Produto cosmético perfeitamente iluminado flutuando sobre um fundo branco puro, com uma sombra suave e realista.' }, examples: ["ecommerce", "product shot", "white background", "online store", "packshot"] },
    { name: "Protetor Solar (Verão)", description: "Cena de verão para produtos de proteção solar.", icon: CosmeticsIcon, preset: { cameraName: 'iPhone 15 Pro (Look de Celular)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz Dura (Brilho Intenso)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Frasco de protetor solar na areia da praia de Copacabana, com conchas, óculos de sol e o mar desfocado ao fundo, sob a luz forte do sol.' }, examples: ["sunscreen", "summer", "beach", "sun care", "sand"] },
    { name: "Maquiagem Noturna (Glamour)", description: "Cena dramática para produtos de maquiagem de festa.", icon: CosmeticsIcon, preset: { cameraName: 'Fuji GFX 100 II + 120mm Macro (Look de Luxo)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Contraluz (Brilho no Produto)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Paleta de sombras com glitter e um batom escuro em uma mesa de festa com confetes dourados e uma taça de champanhe desfocada.' }, examples: ["glamour makeup", "night out", "glitter", "party", "dark lipstick"] },
    { name: "Banho & Corpo", description: "Cena relaxante de spa para produtos de banho.", icon: CosmeticsIcon, preset: { cameraName: 'Canon R5 + 100mm Macro (Cores Vivas)', depthOfFieldName: 'Bokeh Suave (f/4)', lightingName: 'Luz de Janela (Natural)', angle: 'De Cima (Flat Lay)', stylePlaceholder: 'Sabonete artesanal, frasco de loção corporal e uma bomba de banho em uma bandeja de madeira na beira de uma banheira, com pétalas de flores e velas.' }, examples: ["bath and body", "spa", "relax", "lotion", "soap", "bath bomb"] },
    { name: "Pincéis & Acessórios", description: "Foco em detalhes de cerdas e texturas de acessórios.", icon: CosmeticsIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro (Detalhe Extremo)', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'De Cima (Flat Lay)', stylePlaceholder: 'Conjunto de pincéis de maquiagem profissionais dispostos artisticamente sobre uma superfície de mármore, com pó de sombra colorido espalhado ao redor.' }, examples: ["makeup brushes", "sponge", "eyelash curler", "accessories", "flat lay"] }
];

export const cosmeticsStudioConfig = {
    id: 'cosmetics' as const,
    name: "Estúdio de Cosméticos AI",
    specialty: "fotografia de cosméticos",
    presets: COSMETICS_PRESETS,
    cameras: COSMETICS_CAMERAS,
    angles: COSMETICS_CAMERA_ANGLES,
    depthsOfField: COSMETICS_DEPTHS_OF_FIELD,
    lightingStyles: COSMETICS_LIGHTING_STYLES,
};