// constants/electronics.ts
import { Option, StudioPreset } from '../types';
import { 
    CameraIcon, ElectronicsIcon,
    TopDownAngleIcon, FortyFiveDegreeAngleIcon, EyeLevelAngleIcon,
    ExtremeCloseUpAngleIcon,
    DeepDofIcon, SelectiveFocusIcon, MediumDofIcon,
    StudioLightIcon, LowKeyIcon, SideLightIcon, NaturalWindowLightIcon,
} from '../components/icons';

const ELECTRONICS_CAMERAS: Option[] = [
    { name: "Sony a7R V + 90mm Macro (Detalhe Extremo)", short_info: "Resolução e nitidez máximas para publicidade.", keywords: ["sony a7r V", "61 megapixels", "g master macro", "extreme sharpness", "commercial advertising", "metal texture", "ultimate resolution"], icon: CameraIcon, technical_details: { title: "Sony a7R V: A Lupa Digital", description: "O auge da resolução. O sensor de 61MP, combinado com uma lente macro, captura detalhes surreais. É a escolha para publicidade de alto nível, onde cada textura do metal e detalhe do design precisam ser perfeitos.", pro_tips: ["Ideal para grandes impressões ou outdoors.", "O autofoco com IA ajuda a travar o foco precisamente no detalhe desejado.", "Revela texturas em metal escovado e plástico de forma impressionante."] } },
    { name: "Canon R5 + 100mm Macro (Cores Vivas)", short_info: "Ciência de cores renomada para fidelidade.", keywords: ["canon R5", "color accuracy", "dynamic range", "studio electronics", "45MP sensor profile", "true-to-life color"], icon: CameraIcon, technical_details: { title: "Canon R5: A Mestra das Cores", description: "Famosa por sua fidelidade de cor, esta opção é perfeita para capturar a cor exata de um produto. Garante que o 'space gray' de um notebook seja reproduzido com precisão.", pro_tips: ["Excelente para fotografar produtos contra fundos brancos puros para e-commerce.", "A lente RF 100mm Macro revela detalhes incríveis em botões e portas."] } },
    { name: "Fuji GFX 100 II + 120mm Macro (Look de Luxo)", short_info: "Qualidade de médio formato para campanhas.", keywords: ["fujifilm gfx 100 ii", "medium format", "102mp", "luxury electronics", "editorial look", "unmatched detail", "deep color tones"], icon: CameraIcon, technical_details: { title: "Fuji GFX 100 II: O Padrão do Luxo", description: "Um sistema de médio formato que define o padrão para fotografia de luxo. O sensor maior produz imagens com uma profundidade tridimensional e riqueza de cores ideais para marcas de eletrônicos de alta gama.", pro_tips: ["Ideal para campanhas publicitárias e editoriais de revistas de tecnologia.", "As cores são ricas e profundas, perfeitas para embalagens sofisticadas e acabamentos de produtos."] } },
    { name: "iPhone 15 Pro (Look de Celular)", short_info: "Fotografia computacional para redes sociais.", keywords: ["iphone 15 pro", "computational photography", "hdr", "social media look", "sharp and punchy", "macro mode", "e-commerce ready"], icon: CameraIcon, technical_details: { title: "iPhone 15 Pro: O Look das Redes Sociais", description: "Utiliza IA para criar imagens prontas para as redes sociais: nítidas, vibrantes e com HDR impressionante. O modo macro é surpreendentemente capaz de capturar detalhes para posts rápidos.", pro_tips: ["Excelente para criar conteúdo rápido e de alta qualidade para Instagram ou TikTok.", "As cores são otimizadas para telas, fazendo os produtos se destacarem."] } },
];
const ELECTRONICS_DEPTHS_OF_FIELD: Option[] = [
    { name: "Focus Stacking (Nitidez Total)", short_info: "Todo o produto em nitidez perfeita.", keywords: ["focus stacking", "fully sharp", "deep focus electronics", "macro sharp", "aperture f/16", "edge-to-edge sharpness"], icon: DeepDofIcon, technical_details: { title: "Focus Stacking: O Padrão Profissional", description: "Simula a técnica profissional onde múltiplas fotos com diferentes pontos de foco são combinadas para criar uma imagem final onde o produto inteiro, do ponto mais próximo ao mais distante, está perfeitamente nítido.", pro_tips: ["Essencial para teclados, câmeras e smartwatches.", "Garante que cada detalhe do produto seja visível e claro para e-commerce."] } },
    { name: "Foco Seletivo (f/2.8)", short_info: "Destaca um detalhe (botão, logo).", keywords: ["selective macro focus", "shallow dof", "design focus", "detail isolation", "aperture f/2.8", "bokeh"], icon: SelectiveFocusIcon, technical_details: { title: "Foco Seletivo (f/2.8): O Destaque Artístico", description: "Usa uma profundidade de campo rasa (abertura f/2.8) para focar em um único ponto de interesse, como um botão, o logo ou um detalhe de design, deixando o resto em um desfoque suave.", pro_tips: ["Cria imagens de alto impacto para campanhas e redes sociais.", "Ideal para destacar a característica mais importante de um produto."] } },
    { name: "Foco Profundo (f/16)", short_info: "Nitidez de ponta a ponta para catálogos.", keywords: ["deep depth of field", "edge-to-edge sharpness", "aperture f/16", "f/22", "e-commerce", "product isolation"], icon: DeepDofIcon, technical_details: { title: "Foco Profundo (f/16): Clareza para Catálogo", description: "Utiliza uma profundidade de campo muito grande (abertura pequena como f/16) para garantir que grande parte do produto e do seu entorno próximo esteja nítido.", pro_tips: ["Bom para fotos de catálogo e lojas online onde o contexto importa.", "Requer mais luz, ideal para configurações de estúdio com flash."] } },
    { name: "Foco Equilibrado (f/8)", short_info: "Equilíbrio entre foco no produto e no cenário.", keywords: ["medium depth of field", "f/8", "f/11", "balanced focus", "storytelling", "contextual shot"], icon: MediumDofIcon, technical_details: { title: "Foco Equilibrado (f/8): O Equilíbrio Narrativo", description: "Um meio-termo (abertura f/8) que mantém o produto principal em foco nítido, mas permite que o fundo seja reconhecível e contextual. Ideal para contar uma história.", pro_tips: ["Excelente para fotos de lifestyle (ex: notebook em uma mesa).", "Oferece um look mais natural e menos 'clínico' que a nitidez total."] } },
];
const ELECTRONICS_LIGHTING_STYLES: Option[] = [
    { name: "Luz de Estúdio (Softbox Triplo)", short_info: "Iluminação limpa, padrão para e-commerce.", keywords: ["three-point lighting", "clean electronics lighting", "studio shot", "no harsh reflections", "catalog product"], icon: StudioLightIcon, technical_details: { title: "Luz de Estúdio (Softbox Triplo): O Padrão para E-commerce", description: "A configuração clássica para fotografia de produtos. Usa três fontes de luz suave (softboxes) para iluminar o produto de maneira uniforme, eliminando sombras fortes e controlando reflexos.", pro_tips: ["Essencial para fotografar telas e superfícies metálicas ou plásticas.", "Cria um look profissional e limpo, ideal para fundos brancos."] } },
    { name: "Luz Dramática (Estilo Rembrandt)", short_info: "Luz clássica com sombras suaves e profundas.", keywords: ["dramatic lighting", "rembrandt triangle", "soft shadows", "cinematic electronics", "chiaroscuro"], icon: LowKeyIcon, technical_details: { title: "Luz Dramática (Estilo Rembrandt): Drama e Sofisticação", description: "Uma técnica que cria um look dramático, mas suave, que adiciona profundidade e um toque cinematográfico. Ideal para produtos com design arrojado.", pro_tips: ["Excelente para criar uma atmosfera 'moody' e sofisticada.", "Funciona bem com fundos escuros para aumentar o drama e a sensação de produto premium."] } },
    { name: "Luz Lateral Dura (Textura)", short_info: "Realça texturas e formas com alto contraste.", keywords: ["dramatic side light", "texture enhancing", "deep shadows", "hard light", "editorial electronics"], icon: SideLightIcon, technical_details: { title: "Luz Lateral Dura: Esculpindo com Sombras", description: "Uma única fonte de luz forte e sem difusão, posicionada ao lado do produto. Ela cria sombras longas e bem definidas que esculpem a peça. É a melhor técnica para revelar texturas em metal escovado ou plástico texturizado.", pro_tips: ["Use um rebatedor preto no lado oposto para aprofundar as sombras.", "Ideal para produtos com design industrial ou arrojado."] } },
    { name: "Luz de Janela (Natural)", short_info: "Luz suave para um estilo de vida orgânico.", keywords: ["natural window light", "soft diffused light", "organic feel", "lifestyle electronics shot", "daylight"], icon: NaturalWindowLightIcon, technical_details: { title: "Luz de Janela: A Beleza da Simplicidade", description: "A luz suave e difusa que entra por uma janela grande. É perfeita para criar um look de estilo de vida natural e autêntico, mostrando o produto em um ambiente real (ex: um home office).", pro_tips: ["Funciona melhor em dias nublados para uma luz ainda mais suave.", "Posicione o produto perto da janela para aproveitar ao máximo a luz."] } },
];
const ELECTRONICS_CAMERA_ANGLES: Option[] = [
    { name: "Ângulo 45° (Hero Shot)", short_info: "O 'hero shot' versátil e natural.", keywords: ["hero shot", "three-quarter view", "natural perspective", "product photography", "depth perception"], icon: FortyFiveDegreeAngleIcon, technical_details: { title: "Ângulo 45° (Hero Shot): O Padrão Ouro", description: "O ângulo mais comum e eficaz para produtos. Mostra a frente e o lado do item simultaneamente, oferecendo uma visão tridimensional que revela profundidade e design.", pro_tips: ["A escolha ideal para a foto principal do produto.", "Funciona para quase todos os tipos de eletrônicos."] } },
    { name: "De Cima (Flat Lay)", short_info: "Para teclados, mouses e composições.", keywords: ["flat lay", "overhead shot", "catalog electronics", "composition", "desk setup"], icon: TopDownAngleIcon, technical_details: { title: "De Cima (Flat Lay): A Composição Completa", description: "Perfeito para exibir o design de itens que ficam planos, como teclados. Também é o ângulo padrão para 'flat lays' de 'desk setups'.", pro_tips: ["Use para criar 'moodboards' com os produtos, cadernos e outros adereços.", "A iluminação deve ser uniforme para evitar sombras indesejadas."] } },
    { name: "Frontal (Nível do Olhar)", short_info: "Mostra o produto diretamente de frente.", keywords: ["eye-level shot", "head-on view", "direct perspective", "catalog clarity"], icon: EyeLevelAngleIcon, technical_details: { title: "Frontal (Nível do Olhar): A Visão Direta", description: "O ângulo clássico para monitores, notebooks abertos e caixas de som, mostrando o produto de frente. Foca no seu design principal, sendo ideal para fotos de catálogo.", pro_tips: ["Combine com Focus Stacking para nitidez total de frente.", "Ideal para mostrar a marca e a tela de forma clara."] } },
    { name: "Super Close-up (Macro)", short_info: "Foco em detalhes como portas e texturas.", keywords: ["macro detail", "close-up shot", "port detail", "build quality", "metal texture"], icon: ExtremeCloseUpAngleIcon, technical_details: { title: "Super Close-up (Macro): A Qualidade da Construção", description: "Um enquadramento super fechado que revela a qualidade da construção - a textura do metal, o design de um botão ou as portas de conexão. É sobre mostrar a qualidade e a engenharia.", pro_tips: ["Requer uma lente macro e iluminação precisa.", "Revela detalhes que não são visíveis a olho nu, agregando valor ao produto."] } },
];
const ELECTRONICS_PRESETS: StudioPreset[] = [
    { name: "Smartphone (Minimalista)", description: "Mostra o design do celular em um cenário limpo.", icon: ElectronicsIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro (Detalhe Extremo)', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Smartphone moderno exibido em um ângulo sobre um bloco de concreto, com sombras suaves e um fundo de cor sólida e neutra.' }, examples: ["smartphone", "product shot", "clean design", "minimalist background"] },
    { name: "Notebook (Lifestyle)", description: "Cena de produtividade com o notebook em uso.", icon: ElectronicsIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro (Detalhe Extremo)', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz de Janela (Natural)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Notebook aberto em uma mesa de madeira, com uma xícara de café, um caderno e uma planta, em um home office bem iluminado em São Paulo.' }, examples: ["laptop", "workspace", "lifestyle", "coffee", "desk setup"] },
    { name: "Fones de Ouvido (Urbano)", description: "Mostra fones de ouvido em um cenário de estilo de vida urbano.", icon: ElectronicsIcon, preset: { cameraName: 'iPhone 15 Pro (Look de Celular)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz de Janela (Natural)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Fones de ouvido sem fio em uma mesa de café com vista para a Avenida Paulista, com o brilho suave da tarde.' }, examples: ["headphones", "earbuds", "lifestyle", "urban", "city background"] },
    { name: "Smartwatch (Close-up Pulso)", description: "Foco no mostrador e design do smartwatch, em uso.", icon: ElectronicsIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro (Detalhe Extremo)', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'Super Close-up (Macro)', stylePlaceholder: 'Close-up de um smartwatch no pulso de uma pessoa brasileira, mostrando uma interface de fitness, com o fundo de uma academia moderna levemente desfocado.' }, examples: ["smartwatch", "on wrist", "watch face", "close-up", "fitness"] },
    { name: "Câmera Fotográfica (Produto)", description: "Imagem de produto limpa e detalhada de uma câmera.", icon: ElectronicsIcon, preset: { cameraName: 'Canon R5 + 100mm Macro (Cores Vivas)', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Luz Dramática (Estilo Rembrandt)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Câmera DSLR profissional em uma superfície de metal escovado, com iluminação dramática destacando suas texturas e design.' }, examples: ["camera", "dslr", "mirrorless", "product shot", "dramatic lighting"] },
    { name: "Console de Videogame (Setup Gamer)", description: "Cena dinâmica mostrando um console em um ambiente de jogo.", icon: ElectronicsIcon, preset: { cameraName: 'iPhone 15 Pro (Look de Celular)', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz Dramática (Estilo Rembrandt)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Console de videogame moderno ao lado de um controle, em uma mesa de setup gamer com iluminação de neon roxa e azul, monitor ao fundo.' }, examples: ["gaming console", "playstation", "xbox", "gamer setup", "neon lights"] },
    { name: "Tablet (Criativo)", description: "Tablet exibido em um contexto de criatividade ou trabalho.", icon: ElectronicsIcon, preset: { cameraName: 'Canon R5 + 100mm Macro (Cores Vivas)', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz de Janela (Natural)', angle: 'De Cima (Flat Lay)', stylePlaceholder: 'Tablet com um aplicativo de desenho aberto, sobre uma mesa de madeira clara, com uma caneta stylus, xícara de café e plantas.' }, examples: ["tablet", "ipad", "drawing", "creative workspace", "flat lay"] },
    { name: "Drone (Aventura)", description: "Mostra um drone em um cenário de aventura ao ar livre.", icon: ElectronicsIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro (Detalhe Extremo)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz de Janela (Natural)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Drone pronto para decolar de uma rocha no topo da Pedra da Gávea, com o Rio de Janeiro enevoado e o sol da manhã ao fundo.' }, examples: ["drone", "adventure", "outdoors", "mountain landscape", "tech"] },
    { name: "Caixa de Som (Ambiente)", description: "Caixa de som inteligente ou Bluetooth em um ambiente doméstico.", icon: ElectronicsIcon, preset: { cameraName: 'iPhone 15 Pro (Look de Celular)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz de Janela (Natural)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Caixa de som Bluetooth em uma estante de madeira, ao lado de livros de autores brasileiros e uma pequena planta, em uma sala de estar aconchegante.' }, examples: ["bluetooth speaker", "smart speaker", "lifestyle", "living room", "music"] },
    { name: "Teclado Mecânico (Detalhes)", description: "Foco nos detalhes e na iluminação de um teclado gamer/mecânico.", icon: ElectronicsIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro (Detalhe Extremo)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz Lateral Dura (Textura)', angle: 'Super Close-up (Macro)', stylePlaceholder: 'Close-up de um teclado mecânico com iluminação RGB, destacando a textura das teclas, em um fundo escuro e atmosférico.' }, examples: ["mechanical keyboard", "gaming keyboard", "RGB", "close-up", "keycaps"] },
    { name: "E-Reader (Leitura Aconchegante)", description: "E-reader em um cenário relaxante e confortável.", icon: ElectronicsIcon, preset: { cameraName: 'iPhone 15 Pro (Look de Celular)', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz de Janela (Natural)', angle: 'De Cima (Flat Lay)', stylePlaceholder: 'E-reader em uma manta de tricô ao lado de uma xícara de chá e óculos, com a luz suave da janela iluminando a cena.' }, examples: ["e-reader", "kindle", "cozy", "reading", "lifestyle"] },
    { name: "TV & Monitores (Imersivo)", description: "Mostra uma tela com uma imagem vibrante em um ambiente escuro.", icon: ElectronicsIcon, preset: { cameraName: 'Fuji GFX 100 II + 120mm Macro (Look de Luxo)', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz Dramática (Estilo Rembrandt)', angle: 'Frontal (Nível do Olhar)', stylePlaceholder: 'Monitor de tela grande exibindo uma paisagem espacial colorida, em uma sala escura, com iluminação ambiente sutil vindo de trás da tela.' }, examples: ["monitor", "tv", "home theater", "immersive", "vibrant screen"] },
    { name: "VR Headset (Futurista)", description: "Foto de produto de um headset VR com uma estética futurista.", icon: ElectronicsIcon, preset: { cameraName: 'Fuji GFX 100 II + 120mm Macro (Look de Luxo)', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Luz Dramática (Estilo Rembrandt)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Headset de realidade virtual em um pedestal, com linhas de luz de neon azul e roxa refletindo em suas lentes, fundo escuro e tecnológico.' }, examples: ["vr headset", "virtual reality", "futuristic", "tech", "neon"] },
    { name: "Eletrodoméstico (Cozinha Moderna)", description: "Um eletrodoméstico de design em uma cozinha limpa e moderna.", icon: ElectronicsIcon, preset: { cameraName: 'Canon R5 + 100mm Macro (Cores Vivas)', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Máquina de café expresso de aço inoxidável em uma bancada de mármore branco, em uma cozinha moderna e bem iluminada no Brasil.' }, examples: ["kitchen appliance", "coffee machine", "blender", "modern kitchen", "product design"] },
    { name: "Gadgets (Flat Lay)", description: "Composição de vários gadgets em um layout organizado.", icon: ElectronicsIcon, preset: { cameraName: 'Canon R5 + 100mm Macro (Cores Vivas)', depthOfFieldName: 'Foco Profundo (f/16)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'De Cima (Flat Lay)', stylePlaceholder: 'Layout flat lay de gadgets essenciais (smartphone, fones de ouvido, smartwatch, power bank) em um fundo de cor sólida, estilo "tech essentials".' }, examples: ["gadgets", "flat lay", "tech essentials", "everyday carry", "organized"] },
    { name: "Tecnologia Retrô (Nostalgia)", description: "Um dispositivo eletrônico antigo com uma estética vintage.", icon: ElectronicsIcon, preset: { cameraName: 'iPhone 15 Pro (Look de Celular)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz de Janela (Natural)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Um videogame portátil dos anos 90 em uma mesa de madeira, com luz suave da tarde, criando uma atmosfera nostálgica.' }, examples: ["retro tech", "vintage electronics", "gameboy", "walkman", "nostalgia"] }
];

export const electronicsStudioConfig = {
    id: 'electronics' as const,
    name: "Estúdio de Eletrônicos AI",
    specialty: "fotografia de eletrônicos",
    presets: ELECTRONICS_PRESETS,
    cameras: ELECTRONICS_CAMERAS,
    angles: ELECTRONICS_CAMERA_ANGLES,
    depthsOfField: ELECTRONICS_DEPTHS_OF_FIELD,
    lightingStyles: ELECTRONICS_LIGHTING_STYLES,
};