// constants/jewelry.ts
import { Option, StudioPreset } from '../types';
import { 
    CameraIcon, JewelryIcon,
    TopDownAngleIcon, FortyFiveDegreeAngleIcon, EyeLevelAngleIcon, HighAngleIcon, LowAngleIcon,
    SideViewAngleIcon, ExtremeCloseUpAngleIcon, DutchAngleIcon, PovAngleIcon,
    UltraShallowDofIcon, ShallowDofIcon, MediumDofIcon, DeepDofIcon, TiltShiftDofIcon, SelectiveFocusIcon,
    NaturalWindowLightIcon, GoldenHourIcon, HardLightIcon, SoftDiffusedLightIcon, OverheadLightIcon,
    SideLightIcon, BacklightIcon, LowKeyIcon, HighKeyIcon, StudioLightIcon, CandlelightIcon,
    NeonLightIcon, MixedLightIcon, FlashBounceIcon,
} from '../components/icons';

const JEWELRY_CAMERAS: Option[] = [
    { 
        name: "Sony a7R V + 90mm Macro", 
        short_info: "Alta resolução e detalhes extremos.", 
        keywords: ["sony a7r v", "61 megapixels", "g master macro", "extreme sharpness", "liquid detail", "ultimate resolution"], 
        negative_keywords: ["blurry", "soft focus", "low resolution", "noisy", "grainy"], 
        icon: CameraIcon, 
        technical_details: { title: "Sony a7R V: A Lupa Digital", description: "O auge da resolução. O sensor de 61MP, combinado com uma lente macro G Master, captura detalhes surreais. É a escolha para publicidade de alto nível, onde cada faceta e textura precisam ser perfeitas.", pro_tips: ["Ideal para grandes impressões ou outdoors.", "O autofoco com IA ajuda a travar o foco precisamente no detalhe desejado.", "Revela texturas em metais e gemas de forma impressionante."] } 
    },
    { 
        name: "Canon EOS 5D Mark IV + 100mm Macro", 
        short_info: "Excelente para detalhes finos.", 
        keywords: ["canon eos 5d mark iv", "100mm macro", "high detail", "sharp focus", "product photography"], 
        negative_keywords: ["unfocused", "blurry edges", "low detail"], 
        icon: CameraIcon, 
        technical_details: { title: "Canon 5D Mark IV: O Padrão Confiável", description: "Uma DSLR clássica e confiável que foi a base de muitos estúdios de fotografia de produto. Oferece cores ricas e uma renderização de imagem robusta, ideal para detalhes finos.", pro_tips: ["Cores ricas e agradáveis, com a ciência de cores da Canon.", "Uma escolha segura para resultados consistentes e profissionais."] }
    },
    { 
        name: "iPhone 15 Pro (Look de Celular)", 
        short_info: "Fotografia computacional moderna.", 
        keywords: ["iphone 15 pro", "hdr", "social media look", "sharp and punchy", "macro mode", "e-commerce ready"], 
        negative_keywords: ["dslr look", "soft focus", "grainy"], 
        icon: CameraIcon, 
        technical_details: { title: "iPhone 15 Pro: O Look das Redes Sociais", description: "Utiliza IA para criar imagens prontas para as redes sociais: nítidas, vibrantes e com HDR impressionante. O modo macro é surpreendentemente capaz de capturar detalhes em joias para posts rápidos.", pro_tips: ["Excelente para criar conteúdo rápido e de alta qualidade para Instagram ou TikTok.", "As cores são otimizadas para telas, fazendo os produtos se destacarem."] }
    },
    { 
        name: "Nikon Z8 + 105mm Macro", 
        short_info: "Profissional, ideal para detalhes.", 
        keywords: ["nikon z8", "professional workhorse", "macro lens", "product photography", "e-commerce"], 
        negative_keywords: ["amateur look", "unprofessional", "snapshot quality"], 
        icon: CameraIcon, 
        technical_details: { title: "Nikon Z8: A Workhorse Versátil", description: "Uma câmera que combina a qualidade de imagem de ponta da Nikon com um corpo robusto. Garante imagens limpas, detalhadas e com vasto alcance dinâmico, ideais tanto para e-commerce quanto para editoriais de moda.", pro_tips: ["O autofoco 3D-tracking é útil para seguir a joia em fotos com modelos.", "A ausência de obturador mecânico elimina qualquer vibração, crucial para a nitidez em macro."] }
    },
    { 
        name: "Fujifilm GFX 100 II + 120mm Macro", 
        short_info: "Medium format para captura de luxo.", 
        keywords: ["fujifilm gfx 100 ii", "medium format", "102mp", "luxury jewelry", "editorial look"], 
        negative_keywords: ["flat lighting", "lack of depth", "2d look"], 
        icon: CameraIcon, 
        technical_details: { title: "Fuji GFX 100 II: O Padrão do Luxo", description: "Um sistema de médio formato que define o padrão para fotografia de luxo. O sensor maior produz imagens com uma profundidade tridimensional, gradação tonal e riqueza de cores que é impossível de replicar com câmeras menores.", pro_tips: ["Ideal para campanhas publicitárias e editoriais de revistas de luxo.", "As cores são ricas e profundas, perfeitas para ouro e pedras preciosas."] }
    },
    { 
        name: "Leica S3 + 120mm Macro", 
        short_info: "Alta definição e contraste.", 
        keywords: ["leica s3", "medium format dslr", "luxury brand look", "cinematic medium format", "micro-contrast"], 
        negative_keywords: ["flat image", "digital look", "lack of micro-contrast"], 
        icon: CameraIcon, 
        technical_details: { title: "Leica S3: O 'Look' Tridimensional", description: "Combina a qualidade do médio formato com o famoso 'Leica look'. As imagens têm micro-contraste acentuado e uma qualidade tridimensional que faz as joias saltarem da imagem. É a escolha para marcas que buscam uma estética atemporal e cinematográfica.", pro_tips: ["As lentes simuladas são conhecidas por sua nitidez e renderização únicas.", "Produz um look cinematográfico em médio formato, ótimo para fotos de campanha."] }
    },
    { 
        name: "Hasselblad X2D 100C", 
        short_info: "Imagem premium com cores naturais.", 
        keywords: ["hasselblad x2d 100c", "medium format", "natural color solution", "perfect skin tones", "high-end editorial"], 
        negative_keywords: ["unnatural skin tones", "plastic skin", "oversaturated colors"], 
        icon: CameraIcon, 
        technical_details: { title: "Hasselblad X2D 100C: A Ciência da Cor", description: "Esta opção é lendária por sua ciência de cores. A 'Hasselblad Natural Colour Solution' é projetada para produzir cores incrivelmente precisas e tons de pele belíssimos, tornando-a ideal para fotos de joias com modelos.", pro_tips: ["A melhor escolha para quando a precisão da cor da gema é a prioridade número um.", "Excelente para capturar a interação natural entre a joia e a pele."] }
    },
    { 
        name: "Canon EOS R5 + 100mm Macro", 
        short_info: "Alta fidelidade de cor e precisão.", 
        keywords: ["canon eos r5", "color accuracy", "45mp", "true-to-life color", "product photography"], 
        negative_keywords: ["dull colors", "muted tones", "color cast"], 
        icon: CameraIcon, 
        technical_details: { title: "Canon R5: A Mestra das Cores", description: "Famosa por sua fidelidade de cor, esta opção é perfeita para capturar o tom real de metais e as nuances de gemas coloridas. Garante que o ouro pareça ouro e as safiras tenham seu azul verdadeiro.", pro_tips: ["Excelente para fotografar peças contra fundos brancos puros para e-commerce.", "A lente RF 100mm Macro oferece magnificação superior a 1:1, revelando detalhes incríveis."] }
    },
    { 
        name: "Sony A7 III + 85mm f/1.4", 
        short_info: "Excelente para texturas e suavidade.", 
        keywords: ["sony a7 iii", "85mm f/1.4", "portrait lens", "shallow depth of field", "fine jewelry details"], 
        negative_keywords: ["distorted edges", "low contrast", "grainy"], 
        icon: CameraIcon, 
        technical_details: { title: "Sony A7 III + 85mm: Suavidade e Detalhe", description: "Uma combinação clássica para retratos que também se destaca em joias. A lente 85mm f/1.4 é conhecida por sua nitidez no ponto de foco e um desfoque de fundo (bokeh) extremamente suave e cremoso.", pro_tips: ["Ideal para criar um look suave e de luxo.", "A grande abertura permite um excelente isolamento do sujeito."] }
    },
    { 
        name: "Panasonic Lumix S5 II + 70-200mm", 
        short_info: "Flexível para capturas com zoom.", 
        keywords: ["panasonic lumix s5 ii", "70-200mm lens", "versatile zoom", "fine details", "product photography"], 
        negative_keywords: ["low resolution", "zoom distortion", "blurry background"], 
        icon: CameraIcon, 
        technical_details: { title: "Lumix S5 II + 70-200mm: A Flexibilidade do Zoom", description: "Uma lente zoom teleobjetiva oferece grande flexibilidade para enquadrar a joia sem mover a câmera. É ótima para estúdios onde a distância precisa ser ajustada rapidamente.", pro_tips: ["Permite experimentar com diferentes níveis de compressão de fundo.", "Ideal para capturar detalhes à distância."] }
    },
    { 
        name: "Olympus OM-D E-M1 Mark III", 
        short_info: "Compacta, ideal para detalhes rápidos.", 
        keywords: ["olympus om-d", "micro four thirds", "high-res shot", "quick focus", "lifestyle jewelry"], 
        negative_keywords: ["soft focus", "grainy image", "lack of detail"], 
        icon: CameraIcon, 
        technical_details: { title: "Olympus OM-D: Compacta e Poderosa", description: "Uma câmera Micro Four Thirds conhecida por sua estabilização de imagem incrível e o modo 'High-Res Shot', que permite capturar imagens de altíssima resolução sem a necessidade de um sensor grande.", pro_tips: ["O modo 'High-Res Shot' é excelente para fotografia de produto estática.", "Seu tamanho compacto a torna ideal para fotos de lifestyle em locação."] }
    },
    { 
        name: "iPhone 12 Pro Max", 
        short_info: "Fotografia compacta e detalhada.", 
        keywords: ["iphone 12 pro max", "hdr", "social media", "vibrant colors", "sharp details"], 
        negative_keywords: ["digital look", "oversaturated", "low depth of field"], 
        icon: CameraIcon, 
        technical_details: { title: "iPhone 12 Pro Max: O Padrão Moderno", description: "Um smartphone ainda muito capaz, que produz imagens nítidas e vibrantes prontas para redes sociais. A fotografia computacional (HDR) garante um bom equilíbrio de luzes e sombras.", pro_tips: ["Uma opção sólida para conteúdo rápido e de boa qualidade.", "As cores são vivas e atraentes em telas de celular."] }
    },
    { 
        name: "Nikon D850 + 60mm Macro", 
        short_info: "A confiabilidade de uma DSLR clássica.", 
        keywords: ["nikon d850", "dslr", "60mm macro", "true-to-life colors", "detail accuracy"], 
        negative_keywords: ["blurry details", "inconsistent color"], 
        icon: CameraIcon, 
        technical_details: { title: "Nikon D850: A Workhorse do Estúdio", description: "Uma combinação lendária de DSLR que foi o pilar de estúdios de produtos por anos. É conhecida por sua robustez, cores ricas e excelente qualidade de imagem.", pro_tips: ["Oferece cores ricas e realistas, com uma renderização clássica.", "Uma câmera que inspira confiança e entrega resultados consistentes."] }
    },
    { 
        name: "Leica Q2", 
        short_info: "Imagens nítidas e contrastadas.", 
        keywords: ["leica q2", "luxury look", "fine dining", "premium branding", "sharp macro"], 
        negative_keywords: ["flat look", "soft edges", "overexposed"], 
        icon: CameraIcon, 
        technical_details: { title: "Leica Q2: O Luxo Compacto", description: "Uma câmera compacta premium com uma lente Summilux fixa. O 'Leica look' é famoso por seu micro-contraste, que dá uma sensação tridimensional às imagens. O modo macro é surpreendentemente nítido.", pro_tips: ["Produz imagens com um look sofisticado e cinematográfico.", "Ideal para marcas que buscam uma estética de luxo e atemporal."] }
    },
    { 
        name: "Fuji X-T4 + 50mm f/1.8", 
        short_info: "Ótima para captura de texturas e cores.", 
        keywords: ["fujifilm x-t4", "50mm f/1.8", "sharp focus", "natural color", "detail photography"], 
        negative_keywords: ["soft focus", "low contrast"], 
        icon: CameraIcon, 
        technical_details: { title: "Fujifilm X-T4: A Alma Analógica", description: "Famosa por suas simulações de filme, esta opção oferece cores com uma qualidade quase analógica. É perfeita para criar uma atmosfera 'moody' e artística, com tons suaves, ideal para joias artesanais ou com um toque vintage.", pro_tips: ["Cria um look único que se destaca da fotografia de produto tradicional.", "Excelente para marcas com uma forte identidade visual."] }
    }
];

const JEWELRY_CAMERA_ANGLES: Option[] = [
    { name: "Ângulo 45° (Hero Shot)", short_info: "Perspectiva heroica para destaque.", keywords: ["hero shot", "three-quarter view", "natural perspective", "ring photography", "depth perception"], negative_keywords: ["flat lay", "top down", "eye level", "distorted perspective"], icon: FortyFiveDegreeAngleIcon, technical_details: { title: "Ângulo 45° (Hero Shot): O Padrão Ouro", description: "O ângulo mais comum e eficaz para joias. Mostra a frente e o lado da peça simultaneamente, oferecendo uma visão tridimensional que revela profundidade, forma e detalhes. É a visão mais natural, como se estivesse na vitrine.", pro_tips: ["A escolha ideal para a foto principal do produto.", "Funciona para quase todos os tipos de joias, de anéis a brincos."] } },
    { name: "De Cima (Flat Lay)", short_info: "Captura de joias dispostas de forma plana.", keywords: ["flat lay", "overhead shot", "catalog jewelry", "composition", "clean layout"], negative_keywords: ["side view", "45 degree", "low angle", "perspective"], icon: TopDownAngleIcon, technical_details: { title: "De Cima (Flat Lay): A Composição Completa", description: "Perfeito para exibir o design completo de itens que ficam planos, como colares e pulseiras. Também é o ângulo padrão para 'flat lays', onde a joia é composta com outros objetos para contar uma história.", pro_tips: ["Use para criar 'moodboards' com joias, flores e outros adereços.", "A iluminação deve ser uniforme para evitar sombras indesejadas."] } },
    { name: "Frontal (Nível do Olhar)", short_info: "Captura direta e clara.", keywords: ["eye-level shot", "head-on view", "direct perspective", "catalog clarity"], negative_keywords: ["top down", "high angle", "tilted", "angled view"], icon: EyeLevelAngleIcon, technical_details: { title: "Frontal (Nível do Olhar): A Visão Direta", description: "O ângulo clássico para anéis, mostrando a peça de frente, como se estivesse em pé. Faz a joia parecer imponente e foca no seu design principal, sendo ideal para fotos de catálogo.", pro_tips: ["Use um suporte discreto ou cera para manter a peça em pé.", "Combine com Focus Stacking para nitidez total de frente."] } },
    { name: "De Baixo (Imponente)", short_info: "Perspectiva de baixo para cima, imponente.", keywords: ["low angle shot", "imposing jewelry", "masculine look", "heroic perspective", "luxury"], negative_keywords: ["high angle", "top down", "eye level", "flat lay"], icon: LowAngleIcon, technical_details: { title: "De Baixo (Imponente): A Perspectiva Heroica", description: "A câmera é posicionada ligeiramente abaixo da joia, olhando para cima. Isso cria uma perspectiva que torna a peça maior, mais grandiosa e luxuosa. Transmite uma sensação de poder e exclusividade.", pro_tips: ["Excelente para peças statement e anéis com pedras grandes.", "Funciona bem para relógios e joias masculinas."] } },
    { name: "Super Close-up (Macro)", short_info: "Detalhamento extremo das texturas e gemas.", keywords: ["macro detail", "close-up shot", "gemstone cut", "craftsmanship detail", "hallmark"], negative_keywords: ["wide shot", "full view", "environmental shot"], icon: ExtremeCloseUpAngleIcon, technical_details: { title: "Super Close-up (Macro): A Arte da Joalheria", description: "Um enquadramento super fechado que revela a arte da joalheria - a cravação das pedras, a textura do metal, as facetas de uma gema ou a marca do fabricante (hallmark). É sobre mostrar a qualidade e o trabalho artesanal.", pro_tips: ["Requer uma lente macro e iluminação precisa.", "Revela detalhes que não são visíveis a olho nu, agregando valor à peça."] } },
    { name: "De Lado (Perfil)", short_info: "Captura do perfil da joia.", keywords: ["profile shot", "side view", "ring setting detail", "ear jewelry profile", "technical view"], negative_keywords: ["front view", "top down", "angled view"], icon: SideViewAngleIcon, technical_details: { title: "De Lado (Perfil): A Visão Técnica", description: "A câmera é posicionada ao lado da joia, mostrando seu perfil. É crucial para anéis, revelando detalhes da cravação, a galeria sob a pedra e o design da banda. Oferece uma visão técnica e detalhada da construção.", pro_tips: ["Indispensável para anéis de noivado para mostrar a altura da cravação.", "Garante que o cliente veja todos os ângulos da joia."] } },
    { name: "Ângulo Alto (Visão Superior Ampla)", short_info: "Visão ampla e contexto geral.", keywords: ["high angle", "top-down view", "scene overview", "context shot"], negative_keywords: ["low angle", "eye level", "worm's eye view"], icon: HighAngleIcon, technical_details: { title: "Ângulo Alto: A Visão Ampla", description: "Um ângulo alto, mas não um 'flat lay' completo. É ótimo para mostrar a joia em um contexto maior na cena, como um anel em uma mão sobre uma mesa, capturando mais do ambiente ao redor.", pro_tips: ["Use para contar uma história, mostrando a joia em seu ambiente.", "Dá uma sensação de 'espiar' uma cena real."] } },
    { name: "Ponto de Vista (POV Shot)", short_info: "Visão em primeira pessoa, com joia em uso.", keywords: ["point of view", "pov shot", "on-wrist", "first person view", "lifestyle"], negative_keywords: ["third person", "impersonal view", "studio shot"], icon: PovAngleIcon, technical_details: { title: "Ponto de Vista (POV): A Experiência Pessoal", description: "A câmera simula o ponto de vista da pessoa que está usando a joia, olhando para baixo em direção à sua mão, pulso ou peito. Cria uma conexão pessoal e ajuda o cliente a se imaginar usando a peça.", pro_tips: ["Incrivelmente eficaz para relógios, pulseiras e anéis.", "Cria um conteúdo autêntico e 'relatável' para redes sociais."] } },
    { name: "Ângulo Inclinado (Dutch Angle)", short_info: "Ângulo dinâmico e criativo.", keywords: ["dutch tilt", "dutch angle", "editorial shot", "dynamic composition", "tilted frame"], negative_keywords: ["level horizon", "straight lines", "stable shot"], icon: DutchAngleIcon, technical_details: { title: "Ângulo Inclinado (Dutch Angle): Modernidade e Dinamismo", description: "A câmera é intencionalmente inclinada, criando uma composição diagonal que transmite energia, modernidade e um toque artístico. Quebra a formalidade da fotografia de produto tradicional.", pro_tips: ["Use para campanhas de redes sociais para criar imagens mais cativantes.", "Funciona bem com peças de design arrojado e moderno."] } },
    { name: "Ângulo de Detalhe de Mãos (Hand Focus)", short_info: "Foco nas mãos usando a joia.", keywords: ["hand detail", "jewelry on hand", "wrist focus", "ring on hand", "detailed hand shot"], negative_keywords: ["no hands", "flat lay", "blurred hands"], icon: PovAngleIcon, technical_details: { title: "Hand Focus: A Joia em Uso", description: "Um close-up focado nas mãos que estão usando ou interagindo com a joia. Adiciona um elemento humano e de escala, tornando a peça mais desejável.", pro_tips: ["Essencial para anéis e pulseiras.", "A pose e o cuidado com as mãos são cruciais para um resultado profissional."] } },
    { name: "Ângulo de Reflexo (Mirror Reflection)", short_info: "Joias capturadas em reflexo.", keywords: ["mirror reflection", "jewelry in mirror", "reflective surface", "gem reflection", "creative jewelry shot"], negative_keywords: ["unclear reflection", "blurry mirror", "distorted reflection"], icon: MixedLightIcon, technical_details: { title: "Reflexo: O Jogo de Espelhos", description: "Utiliza espelhos ou superfícies reflexivas para criar composições criativas, mostrando múltiplos ângulos da joia simultaneamente ou criando um efeito de profundidade.", pro_tips: ["Adiciona um toque de sofisticação e mistério à imagem.", "O controle da iluminação é essencial para evitar reflexos indesejados."] } },
    { name: "Ângulo de Cima para Baixo (Bird's Eye View)", short_info: "Visão de cima para baixo, ampla.", keywords: ["bird’s eye view", "top down", "jewelry layout", "overhead jewelry shot", "scene overview"], negative_keywords: ["low angle", "eye level", "too wide shot"], icon: HighAngleIcon, technical_details: { title: "Bird's Eye View: A Cena Completa", description: "Similar a um flat lay, mas de uma distância maior, capturando uma visão mais ampla da cena. É excelente para mostrar a interação entre várias peças e elementos decorativos.", pro_tips: ["Funciona bem para editoriais e composições temáticas.", "A organização dos elementos é crucial para o sucesso."] } },
    { name: "Ângulo de Posição de Movimento (Motion Angle)", short_info: "Dinamismo na captura de joias em movimento.", keywords: ["motion shot", "dynamic jewelry", "jewelry in action", "bracelet movement", "ring in use"], negative_keywords: ["no movement", "blurry", "static shot"], icon: DutchAngleIcon, technical_details: { title: "Movimento: A Joia em Ação", description: "Captura a joia em um contexto de movimento, como uma pulseira balançando no pulso ou um colar em uma pessoa dançando. Adiciona dinamismo e uma sensação de vida à imagem.", pro_tips: ["Requer uma velocidade de obturador alta (simulada) para congelar o movimento.", "Cria imagens energéticas e cativantes."] } },
    { name: "Ângulo de Baixo para Cima (Low to High)", short_info: "Perspectiva imponente de baixo para cima.", keywords: ["low to high angle", "powerful jewelry shot", "large jewelry", "dynamic angle", "imposing view"], negative_keywords: ["high to low angle", "eye level", "flat lay"], icon: LowAngleIcon, technical_details: { title: "De Baixo para Cima: A Perspectiva Heroica", description: "A câmera é posicionada abaixo da joia, olhando para cima. Isso cria uma perspectiva que torna a peça maior, mais grandiosa e luxuosa. Transmite uma sensação de poder e exclusividade.", pro_tips: ["Excelente para peças statement e anéis com pedras grandes.", "Funciona bem para relógios e joias masculinas."] } },
    { name: "Ângulo de Lateral (Side Profile)", short_info: "Captura da silhueta da joia.", keywords: ["side profile", "profile view", "jewelry silhouette", "detailed side view", "bracelet profile"], negative_keywords: ["front view", "top down", "tilted angle"], icon: SideViewAngleIcon, technical_details: { title: "Perfil: A Visão Técnica", description: "A câmera é posicionada ao lado da joia, mostrando seu perfil. É crucial para anéis, revelando detalhes da cravação e o design da banda. Oferece uma visão técnica e detalhada da construção.", pro_tips: ["Indispensável para anéis de noivado para mostrar a altura da cravação.", "Garante que o cliente veja todos os ângulos da joia."] } }
];

const JEWELRY_LIGHTING_STYLES: Option[] = [
    { name: "Luz de Estúdio (Softbox Triplo)", short_info: "Iluminação suave e uniforme.", keywords: ["softbox lighting", "even lighting", "studio shot", "product photography", "no harsh reflections"], negative_keywords: ["hard light", "high contrast"], icon: StudioLightIcon, technical_details: { title: "Luz de Estúdio (Softbox Triplo): O Padrão para E-commerce", description: "A configuração clássica para fotografia de produtos. Usa três fontes de luz suave (softboxes) para iluminar a peça de maneira uniforme, eliminando sombras fortes e destacando a forma do material sem criar brilhos que distraiam.", pro_tips: ["Essencial para fotografar metais polidos e relógios.", "Cria um look profissional e limpo, ideal para fundos brancos."] } },
    { name: "Luz Dramática (Estilo Rembrandt)", short_info: "Criando sombras profundas e dramáticas.", keywords: ["dramatic lighting", "rembrandt triangle", "soft shadows", "cinematic jewelry", "chiaroscuro"], negative_keywords: ["flat lighting", "high key", "bright background", "no shadows"], icon: LowKeyIcon, technical_details: { title: "Luz Dramática (Estilo Rembrandt): Drama e Sofisticação", description: "Uma técnica de iluminação clássica que cria um pequeno triângulo de luz no lado sombreado da peça. É conhecida por seu look dramático, mas suave, que adiciona profundidade e um toque cinematográfico.", pro_tips: ["Excelente para criar uma atmosfera 'moody' e sofisticada.", "Funciona bem com fundos escuros para aumentar o drama e a sensação de luxo."] } },
    { name: "Luz Lateral Dura (Textura)", short_info: "Sombras acentuadas para texturas.", keywords: ["hard side light", "texture enhancing", "deep shadows", "hard light", "editorial jewelry"], negative_keywords: ["soft light", "diffused light", "no shadows"], icon: HardLightIcon, technical_details: { title: "Luz Lateral Dura: Esculpindo com Sombras", description: "Uma única fonte de luz forte e sem difusão, posicionada ao lado da joia. Ela cria sombras longas e bem definidas que esculpem a peça. É a melhor técnica para revelar texturas em metais escovados ou detalhes em relevo.", pro_tips: ["Use um rebatedor preto no lado oposto para aprofundar as sombras.", "Ideal para peças masculinas ou com design arrojado e moderno."] } },
    { name: "Luz de Fim de Tarde (Golden Hour)", short_info: "Luz suave e quente.", keywords: ["golden hour", "warm glow", "sunset look", "lifestyle jewelry", "soft light"], negative_keywords: ["cool tones", "blue light", "midday sun", "harsh shadows"], icon: GoldenHourIcon, technical_details: { title: "Luz de Fim de Tarde (Golden Hour): Luxo e Calidez", description: "Simula a luz quente, suave e dourada do pôr do sol. Cria uma atmosfera luxuosa, orgânica e convidativa, perfeita para fotos de estilo de vida e campanhas em redes sociais.", pro_tips: ["Funciona bem com modelos ou em cenários naturais.", "Realça o brilho de ouro amarelo e pedras quentes como rubis."] } },
    { name: "Contraluz (Brilho na Gema)", short_info: "Iluminação por trás para destacar o brilho.", keywords: ["backlighting", "gemstone glow", "backlit jewelry", "shiny jewelry", "radiant effect"], negative_keywords: ["overexposed", "lack of detail", "soft lighting"], icon: BacklightIcon, technical_details: { title: "Contraluz: O Brilho da Gema", description: "A luz principal vem de trás da joia, passando através de pedras translúcidas e criando um brilho interno. Também cria um contorno luminoso (rim light) ao redor da peça, separando-a do fundo.", pro_tips: ["Ideal para diamantes e safiras para mostrar sua clareza e brilho interno.", "Use um pequeno rebatedor na frente para adicionar detalhe à parte frontal.", "Cria um look mágico e etéreo."] } },
    { name: "Luz Circular (Ring Light)", short_info: "Brilho suave com reflexos nos olhos.", keywords: ["ring light", "soft lighting", "catchlight", "reflection", "social media jewelry"], negative_keywords: ["harsh shadows", "no catchlight", "multiple reflections"], icon: StudioLightIcon, technical_details: { title: "Luz Circular (Ring Light): Modernidade e Perfeição", description: "Uma fonte de luz em anel que cria uma iluminação frontal uniforme e quase sem sombras. Seu diferencial é o reflexo circular perfeito que cria em superfícies reflexivas, como gemas e metais.", pro_tips: ["Muito popular para vídeos e fotos para redes sociais.", "Cria um brilho limpo e futurista no olho de um modelo ou na superfície de uma gema."] } },
    { name: "Luz Dura (Brilho Intenso)", short_info: "Iluminação intensa para reflexos nítidos.", keywords: ["hard light", "bright highlights", "intense reflections", "jewelry details", "luxury jewelry"], negative_keywords: ["soft lighting", "low contrast", "dull"], icon: HardLightIcon, technical_details: { title: "Luz Dura: O Brilho das Facetas", description: "Vem de uma fonte de luz pequena e sem difusão (como o sol do meio-dia ou um flash direto), criando sombras de bordas nítidas e realces especulares (brilhos) intensos. É uma escolha ousada que pode realçar drasticamente as facetas de um diamante.", pro_tips: ["Use para criar um look dramático e de alto contraste.", "As sombras podem ser usadas como um elemento de composição forte."] } },
    { name: "Polarização Cruzada (Sem Reflexos)", short_info: "Elimina reflexos e garante cores reais.", keywords: ["cross polarization", "no glare", "true color", "product photography", "crystal-clear"], negative_keywords: ["glare", "reflections", "blown highlights"], icon: StudioLightIcon, technical_details: { title: "Polarização Cruzada: Controle Total", description: "Uma técnica avançada que usa filtros polarizadores tanto na lente quanto nas fontes de luz. Ao cruzá-los, é possível eliminar quase todos os reflexos especulares, revelando a cor e a textura puras do material sem brilhos que distraiam.", pro_tips: ["A melhor técnica para fotografar gemas coloridas sem reflexos.", "Ideal para relógios, para eliminar reflexos no cristal e no metal polido."] } },
    { name: "Light Painting (Luz Artística)", short_info: "Criando efeitos artísticos com luz.", keywords: ["light painting", "artistic light", "long exposure", "creative jewelry shot", "dramatic effect"], negative_keywords: ["motion blur", "lack of focus", "overexposure"], icon: MixedLightIcon, technical_details: { title: "Light Painting: A Joia como Tela", description: "Uma técnica criativa que envolve uma longa exposição em um ambiente escuro, enquanto pequenas fontes de luz (como uma lanterna ou fibra óptica) são movidas para 'pintar' luz seletivamente em partes da joia.", pro_tips: ["Permite um controle artístico total sobre quais partes da joia são destacadas.", "Cria um look etéreo com rastros de luz e brilhos suaves e controlados."] } },
    { name: "Luz de Janela (Natural)", short_info: "Luz suave e natural.", keywords: ["natural window light", "soft diffused light", "organic feel", "lifestyle jewelry", "daylight"], negative_keywords: ["hard light", "studio lighting", "flash"], icon: NaturalWindowLightIcon, technical_details: { title: "Luz de Janela: A Beleza da Simplicidade", description: "A luz suave e difusa que entra por uma janela grande (idealmente voltada para o norte, para evitar sol direto). É perfeita para criar um look de estilo de vida natural, orgânico e autêntico, mostrando a joia em um ambiente real.", pro_tips: ["Funciona melhor em dias nublados para uma luz ainda mais suave.", "Posicione o modelo ou a peça perto da janela para aproveitar ao máximo a luz e criar sombras suaves."] } },
    { name: "Luz de Neon (Urbano e Colorido)", short_info: "Luz vibrante e colorida.", keywords: ["neon light", "colored gels", "urban jewelry", "street style", "vibrant lighting"], negative_keywords: ["low contrast", "dull colors", "washed-out effect"], icon: NeonLightIcon, technical_details: { title: "Luz de Neon: O Brilho Urbano", description: "Usa luzes de neon ou géis coloridos para criar um look urbano, noturno e vibrante. Ideal para joias modernas, campanhas de moda com tema noturno e para criar um visual que se destaca nas redes sociais.", pro_tips: ["Combine cores complementares para um efeito visualmente impactante.", "Abrace os reflexos coloridos nos metais como parte da estética."] } },
    { name: "Flash Direto (Look Editorial/Cru)", short_info: "Flash direto para um look moderno.", keywords: ["direct flash", "harsh lighting", "editorial jewelry", "high contrast", "flash photography"], negative_keywords: ["soft light", "no contrast", "washed out"], icon: FlashBounceIcon, technical_details: { title: "Flash Direto: O Look Editorial", description: "Uma escolha estilística ousada que usa o flash direto na câmera. Cria sombras duras, realces especulares intensos e um alto contraste. O resultado é um look 'cru', editorial e moderno, popular em revistas de moda.", pro_tips: ["Funciona bem para criar um clima de 'paparazzi' de luxo.", "Não é sobre perfeição técnica, mas sobre atitude e impacto visual."] } },
    { name: "High-Key (Brilhante e Leve)", short_info: "Iluminação clara e leve.", keywords: ["high key", "bright background", "airy look", "clean jewelry photography", "bright tones"], negative_keywords: ["low key", "high contrast", "dark background"], icon: HighKeyIcon, technical_details: { title: "High-Key: Pureza e Leveza", description: "Esta técnica usa iluminação abundante para criar uma cena predominantemente clara, muitas vezes com um fundo branco puro e sombras mínimas. O resultado é um look limpo, arejado e etéreo.", pro_tips: ["Ideal para e-commerce em fundo branco e para joias delicadas como prata e diamantes.", "Transmite uma sensação de pureza, simplicidade e luxo minimalista."] } },
    { name: "Luz de Cima (Top-Down para Flat Lays)", short_info: "Luz direta de cima.", keywords: ["top-down light", "flat lay photography", "even lighting", "overhead jewelry shot", "catalog jewelry"], negative_keywords: ["side lighting", "uneven lighting", "flat image"], icon: OverheadLightIcon, technical_details: { title: "Luz de Cima: A Luz do Flat Lay", description: "Uma grande fonte de luz suave posicionada diretamente acima da joia. É a configuração ideal para fotos 'flat lay', pois fornece uma iluminação uniforme e minimiza sombras que poderiam distrair da composição.", pro_tips: ["Essencial para exibir o design completo de colares e pulseiras.", "Pode ser combinada com pequenos rebatedores para adicionar brilho em pontos específicos."] } },
    { name: "Luz Quente de Ambiente (Intimista)", short_info: "Iluminação suave e intimista.", keywords: ["ambient warm light", "cozy jewelry shot", "soft glow", "romantic jewelry", "luxury lighting"], negative_keywords: ["cool tones", "overexposure", "hard shadows"], icon: CandlelightIcon, technical_details: { title: "Luz Quente de Ambiente: Aconchego e Intimidade", description: "Simula a luz de lâmpadas incandescentes, velas ou uma lareira. Cria uma atmosfera quente, íntima e acolhedora, perfeita para associar a joia a momentos especiais e pessoais.", pro_tips: ["Ideal para campanhas de Dia dos Namorados ou de inverno.", "Realça o brilho de ouro amarelo e pedras de tons quentes."] } }
];

const JEWELRY_DEPTHS_OF_FIELD: Option[] = [
    { name: "Focus Stacking (Nitidez Total)", short_info: "Toda a joia em nitidez perfeita.", keywords: ["focus stacking", "fully sharp", "deep focus jewelry", "macro sharp", "aperture f/16", "edge-to-edge sharpness"], negative_keywords: ["blurry edges", "soft focus", "shallow depth of field", "out of focus parts"], icon: DeepDofIcon, technical_details: { title: "Focus Stacking: O Padrão Profissional", description: "Simula a técnica profissional onde múltiplas fotos com diferentes pontos de foco são combinadas para criar uma imagem final onde a joia inteira, do ponto mais próximo ao mais distante, está perfeitamente nítida.", pro_tips: ["Essencial para relógios e anéis complexos.", "Garante que cada detalhe da peça seja visível e claro para e-commerce."] } },
    { name: "Foco Seletivo (f/2.8)", short_info: "Destaca um único ponto (gema, cravação).", keywords: ["selective macro focus", "shallow dof", "gemstone focus", "detail isolation", "aperture f/2.8", "bokeh"], negative_keywords: ["deep focus", "everything sharp", "flat image", "sharp background"], icon: SelectiveFocusIcon, technical_details: { title: "Foco Seletivo (f/2.8): O Destaque Artístico", description: "Usa uma profundidade de campo rasa (abertura f/2.8) para focar em um único ponto de interesse, como o diamante principal de um anel, deixando o resto em um desfoque suave e artístico (bokeh).", pro_tips: ["Cria imagens de alto impacto para campanhas e redes sociais.", "Ideal para destacar a característica mais importante de uma peça."] } },
    { name: "Bokeh Suave (f/4)", short_info: "Look suave e etéreo, bom para pérolas.", keywords: ["soft focus", "dreamy look", "ethereal jewelry", "pearl photography", "aperture f/4", "natural bokeh background"], negative_keywords: ["harsh bokeh", "distracting background", "sharp background", "deep focus"], icon: ShallowDofIcon, technical_details: { title: "Bokeh Suave (f/4): O Toque Delicado", description: "Um desfoque de fundo suave (abertura f/4) que cria uma atmosfera delicada e brilhante. Não busca a nitidez extrema, mas sim uma sensação de leveza e luxo, com um bokeh de fundo natural.", pro_tips: ["Perfeito para pérolas e joias com um design mais orgânico e suave.", "Funciona bem com iluminação difusa para um look ainda mais delicado."] } },
    { name: "Foco Profundo (f/16)", short_info: "Nitidez de ponta a ponta para catálogos.", keywords: ["deep depth of field", "edge-to-edge sharpness", "aperture f/16", "f/22", "e-commerce", "product isolation"], negative_keywords: ["blurry background", "shallow depth of field", "bokeh", "soft focus"], icon: DeepDofIcon, technical_details: { title: "Foco Profundo (f/16): Clareza para Catálogo", description: "Utiliza uma profundidade de campo muito grande (abertura pequena como f/16) para garantir que grande parte da joia e do seu entorno próximo esteja nítida. Não é tão extremo quanto o focus stacking, mas oferece grande clareza.", pro_tips: ["Bom para fotos de catálogo e lojas online onde o contexto importa.", "Requer mais luz, ideal para configurações de estúdio com flash."] } },
    { name: "Foco Equilibrado (f/8)", short_info: "Equilíbrio entre foco na joia e no cenário.", keywords: ["medium depth of field", "f/8", "f/11", "balanced focus", "storytelling", "contextual shot"], negative_keywords: ["extreme blur", "everything sharp", "flat image", "no depth"], icon: MediumDofIcon, technical_details: { title: "Foco Equilibrado (f/8): O Equilíbrio Narrativo", description: "Um meio-termo (abertura f/8) que mantém a joia principal em foco nítido, mas permite que o fundo seja reconhecível e contextual, sem o desfoque extremo. Ideal para contar uma história.", pro_tips: ["Excelente para fotos de lifestyle onde o ambiente é importante.", "Oferece um look mais natural e menos 'clínico' que a nitidez total."] } },
    { name: "Bokeh Extremo (Ultra Raso f/1.2)", short_info: "Desfoque máximo para um look etéreo.", keywords: ["ultra shallow dof", "dreamy bokeh", "ethereal jewelry", "f/1.2 prime lens", "artistic blur"], negative_keywords: ["sharp background", "deep focus", "everything in focus", "distracting background"], icon: UltraShallowDofIcon, technical_details: { title: "Profundidade Ultra Rasa (f/1.2)", description: "Leva o 'fundo desfocado' a um novo nível, simulando lentes com aberturas extremas (f/1.2). Apenas uma fina fatia da joia fica em foco, enquanto o fundo se dissolve em um 'bokeh' suave e cremoso, ideal para um look sonhador e artístico.", pro_tips: ["Ideal para um look sonhador, etéreo e de alta classe.", "Cria uma separação dramática entre o sujeito e o fundo."] } },
    { name: "Macro Extremo (Textura)", short_info: "Foco em texturas minúsculas e detalhes.", keywords: ["extreme macro", "razor thin focus", "hallmark detail", "gemstone inclusion", "texture"], negative_keywords: ["wide shot", "full product view", "blurry details"], icon: SelectiveFocusIcon, technical_details: { title: "Foco Macro Extremo", description: "Foca em uma porção minúscula da peça para revelar texturas, marcações (hallmarks) ou inclusões em gemas que não são visíveis a olho nu. A profundidade de campo é incrivelmente rasa.", pro_tips: ["Use para destacar a qualidade artesanal ou características únicas do material.", "Cria imagens abstratas e de alto impacto que valorizam a peça."] } },
    { name: "Efeito Tilt-Shift (Foco Criativo)", short_info: "Cria uma faixa de foco linear em macro.", keywords: ["tilt-shift effect", "macro", "linear focus plane", "diorama effect", "artistic"], negative_keywords: ["normal focus", "even blur", "no focus plane"], icon: TiltShiftDofIcon, technical_details: { title: "Efeito Tilt-Shift: Foco Incomum", description: "Simula o efeito de uma lente tilt-shift, criando uma faixa de foco linear e nítida através de um detalhe da joia, enquanto o resto é desfocado. O resultado é um 'efeito maquete' em escala micro, altamente artístico.", pro_tips: ["Use para criar uma linha de foco diagonal através de um relógio ou bracelete.", "Direciona o olhar do espectador de uma forma única e inesperada."] } }
];

const JEWELRY_PRESETS: StudioPreset[] = [
    { name: "Anel Solitário (Clássico)", keywords: ["solitary ring", "engagement ring", "gemstone focus", "high detail", "luxury jewelry"], description: "O clássico anel de noivado.", icon: JewelryIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Polarização Cruzada (Sem Reflexos)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Anel solitário de diamante exibido sobre uma superfície de mármore polido em uma joalheria de luxo na Rua Oscar Freire, reflexos sutis de vitrine, caixa de veludo aberta ao fundo.' }, examples: ["ring", "diamond sparkle", "sharp detail", "catalog jewelry", "luxury"] },
    { name: "Colar (Flat Lay)", keywords: ["necklace flat lay", "jewelry catalog", "overhead shot", "clean composition"], description: "Captura de colar dispostos de forma plana.", icon: JewelryIcon, preset: { cameraName: 'Nikon Z8 + 105mm Macro', depthOfFieldName: 'Foco Profundo (f/16)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'De Cima (Flat Lay)', stylePlaceholder: 'Colar delicado de ouro disposto sobre uma mesa de madeira clara em ateliê de um designer brasileiro, ferramentas de ourives espalhadas ao redor, fundo suave criando sensação de autenticidade.' }, examples: ["necklace", "top-down jewelry", "flat lay", "e-commerce", "clean background"] },
    { name: "Brincos (em Modelo)", keywords: ["earrings", "model wearing earrings", "lifestyle jewelry", "ear jewelry", "portrait", "modelo brasileira"], description: "Brincos fotografados com o modelo.", icon: JewelryIcon, preset: { cameraName: 'Hasselblad X2D 100C', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz de Fim de Tarde (Golden Hour)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Brincos de pedras brasileiras usados por uma modelo brasileira em um ensaio na praia de Fernando de Noronha ao pôr do sol, cabelos levemente presos, luz dourada refletindo na pele.' }, examples: ["earrings", "lifestyle portrait", "soft light", "natural skin tones", "fashion"] },
    { name: "Relógio de Luxo (Close-up)", keywords: ["luxury watch", "detailed close-up", "luxury timepiece", "high-end watch"], description: "Close-up de relógios finos.", icon: JewelryIcon, preset: { cameraName: 'Fujifilm GFX 100 II + 120mm Macro', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Luz Dramática (Estilo Rembrandt)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Relógio de aço com mostrador preto apoiado em mesa de pedra escura, velas acesas ao fundo em um restaurante sofisticado em São Paulo, atmosfera de editorial de moda.' }, examples: ["luxury watch", "editorial jewelry", "high contrast", "moody style"] },
    { name: "Relógio Esportivo (Aventura)", keywords: ["sports watch", "adventure lifestyle", "technical watch", "rugged design", "outdoor gear"], description: "Relógio esportivo em estilo de vida.", icon: JewelryIcon, preset: { cameraName: 'Nikon Z8 + 105mm Macro', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz de Janela (Natural)', angle: 'De Lado (Perfil)', stylePlaceholder: 'Relógio esportivo no pulso de uma pessoa, apoiado sobre uma rocha com musgo na Chapada Diamantina, fundo de cachoeira desfocado, luz natural filtrada pelas árvores.' }, examples: ["sport watch", "lifestyle", "adventure", "on wrist", "natural background"] },
    { name: "Pulseirismo (Lifestyle)", keywords: ["bracelet lifestyle", "wrist jewelry", "casual style", "wearable accessories", "bracelet photography", "modelo brasileira"], description: "Fotografia de pulseiras no dia a dia.", icon: JewelryIcon, preset: { cameraName: 'Canon EOS R5 + 100mm Macro', depthOfFieldName: 'Bokeh Suave (f/4)', lightingName: 'Luz de Janela (Natural)', angle: 'De Baixo (Imponente)', stylePlaceholder: 'Mix de pulseiras de prata e pedras brasileiras no pulso de uma pessoa segurando uma xícara de café em um café charmoso no Leblon (Rio de Janeiro), com a cidade desfocada ao fundo.' }, examples: ["bracelets", "stacked bracelets", "on wrist", "fashion jewelry", "soft reflections"] },
    { name: "Alianças (Romântico)", keywords: ["wedding ring", "engagement ring", "romantic jewelry", "symbol of love"], description: "Alianças de casamento em foco.", icon: JewelryIcon, preset: { cameraName: 'Sony a7R V + 90mm Macro', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'Frontal (Nível do Olhar)', stylePlaceholder: 'Par de alianças de ouro apoiadas em um livro aberto com páginas finas, pétalas de rosa espalhadas ao redor, taça de champanhe ao fundo, clima romântico.' }, examples: ["wedding rings", "catalog shot", "commercial jewelry", "sharp edges"] },
    { name: "Acessórios Masculinos", keywords: ["masculine jewelry", "luxury accessories", "men's fashion", "bracelets", "rings"], description: "Acessórios masculinos com foco em estilo.", icon: JewelryIcon, preset: { cameraName: 'Leica S3 + 120mm Macro', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Luz Lateral Dura (Textura)', angle: 'De Baixo (Imponente)', stylePlaceholder: 'Pulseira masculina de couro e aço, ao lado de um relógio esportivo, sobre uma mesa de concreto em um bar na Vila Madalena, luz dramática criando sombras definidas.' }, examples: ["men's jewelry", "men's watch", "leather bracelet", "editorial campaign", "sharp focus"] },
    { name: "Joias Delicadas (Minimalista)", keywords: ["minimalist jewelry", "delicate rings", "fine details", "subtle elegance"], description: "Joias finas e discretas.", icon: JewelryIcon, preset: { cameraName: 'iPhone 15 Pro (Look de Celular)', depthOfFieldName: 'Bokeh Suave (f/4)', lightingName: 'Luz Circular (Ring Light)', angle: 'De Cima (Flat Lay)', stylePlaceholder: 'Colar minimalista de prata apoiado em prato de cerâmica branca, fundo liso e claro, estética clean e moderna, em um café contemporâneo em São Paulo.' }, examples: ["minimalist jewelry", "flat lay shot", "ring light reflection", "modern style"] },
    { name: "Brincos (E-commerce)", keywords: ["earrings", "product photography", "jewelry e-commerce", "clear background", "sharp details"], description: "Fotografia de brincos para e-commerce.", icon: JewelryIcon, preset: { cameraName: 'Canon EOS R5 + 100mm Macro', depthOfFieldName: 'Focus Stacking (Nitidez Total)', lightingName: 'Polarização Cruzada (Sem Reflexos)', angle: 'Frontal (Nível do Olhar)', stylePlaceholder: 'Par de brincos pendurados em suporte acrílico transparente, fundo branco minimalista, reflexos controlados sem sombras, ambiente de estúdio limpo e profissional.' }, examples: ["earrings product shot", "focus stacking", "edge-to-edge sharpness", "clean background"] },
    { name: "Piercings (Close-up Orelha)", keywords: ["ear piercing", "close-up jewelry", "ear accessories", "precise detail", "earrings", "modelo brasileira"], description: "Foco nos piercings de orelha.", icon: JewelryIcon, preset: { cameraName: 'Canon EOS R5 + 100mm Macro', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz de Janela (Natural)', angle: 'De Lado (Perfil)', stylePlaceholder: 'Piercing de ouro minimalista fotografado em close-up na orelha de modelo brasileira, pele iluminada suavemente por luz natural, fundo desfocado com plantas modernas.' }, examples: ["luxury piercing", "ear jewelry close-up", "delicate sparkle", "fashion piercing"] },
    { name: "Joia Corporal (Praia)", keywords: ["body jewelry", "beach lifestyle", "delicate jewelry", "sunset light", "beach accessories", "modelo brasileira"], description: "Joias corporais no cenário de praia.", icon: JewelryIcon, preset: { cameraName: 'Hasselblad X2D 100C', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz de Fim de Tarde (Golden Hour)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Corrente de corpo dourada usada por modelo brasileira em ensaio na praia de Ipanema, areia e mar desfocados ao fundo, luz natural intensa criando reflexos metálicos na pele bronzeada.' }, examples: ["body chain", "cinematic jewelry", "fashion campaign", "natural light", "beach"] }
];

export const jewelryStudioConfig = {
    id: 'jewelry' as const,
    name: "Estúdio de Joias AI",
    specialty: "fotografia de joias",
    presets: JEWELRY_PRESETS,
    cameras: JEWELRY_CAMERAS,
    angles: JEWELRY_CAMERA_ANGLES,
    depthsOfField: JEWELRY_DEPTHS_OF_FIELD,
    lightingStyles: JEWELRY_LIGHTING_STYLES,
};
