// constants/people.ts
import { Option, StudioPreset } from '../types';
import { 
    CameraIcon, PeopleIcon,
    TopDownAngleIcon, FortyFiveDegreeAngleIcon, EyeLevelAngleIcon, HighAngleIcon, LowAngleIcon,
    SideViewAngleIcon, ExtremeCloseUpAngleIcon, DutchAngleIcon, PovAngleIcon,
    UltraShallowDofIcon, ShallowDofIcon, MediumDofIcon, DeepDofIcon, TiltShiftDofIcon, SelectiveFocusIcon,
    NaturalWindowLightIcon, GoldenHourIcon, HardLightIcon, SoftDiffusedLightIcon, OverheadLightIcon,
    SideLightIcon, BacklightIcon, LowKeyIcon, HighKeyIcon, StudioLightIcon, CandlelightIcon,
    NeonLightIcon, MixedLightIcon, FlashBounceIcon, ColoredGelsIcon,
} from '../components/icons';

const PEOPLE_CAMERAS: Option[] = [
    { name: "Nikon Z7 II 85mm f/1.8 (Fundo Comprimido)", short_info: "Compressão elegante, ideal para retratos.", keywords: ["nikon z7 ii", "telephoto portrait lens", "compression look", "elegant depth", "flattering portrait"], icon: CameraIcon, technical_details: { title: "Nikon 85mm: O Clássico do Retrato", description: "Uma lente teleobjetiva curta como a 85mm comprime a perspectiva, fazendo com que o fundo pareça mais próximo e mais desfocado. É extremamente lisonjeira para rostos, tornando-a a escolha clássica para retratos.", pro_tips: ["Afaste-se do sujeito para obter o enquadramento desejado.", "O desfoque (bokeh) é extremamente suave e agradável.", "Ideal para isolar a pessoa de um fundo complexo de forma limpa e profissional."] } },
    { name: "Sony A7 IV 35mm f/1.4 (Estilo Lifestyle)", short_info: "Perspectiva ampla para fotos de lifestyle.", keywords: ["sony a7 iv", "mirrorless", "wide perspective", "balanced colors", "lifestyle portrait", "environmental shot"], icon: CameraIcon, technical_details: { title: "Sony 35mm: A Contadora de Histórias", description: "A lente de 35mm oferece um campo de visão mais amplo, permitindo incluir mais do ambiente na foto. É ideal para contar uma história, mostrando a pessoa em seu contexto, como em um café ou em sua casa.", pro_tips: ["Ótima para retratos ambientais que mostram a profissão ou hobby da pessoa.", "Aberturas amplas como f/1.4 criam um desfoque suave, mesmo em uma lente mais larga."] } },
    { name: "Canon EOS R5 50mm f/1.8 (Look Natural de Lifestyle)", short_info: "Lente versátil para fotos com modelos.", keywords: ["canon 50mm", "lifestyle portrait", "natural look", "candid photography", "soft bokeh"], icon: CameraIcon, technical_details: { title: "Canon 50mm: O Look Natural", description: "Uma lente clássica que oferece uma perspectiva natural, similar ao olho humano. É ideal para fotografia de estilo de vida, capturando momentos de forma autêntica com um desfoque de fundo suave e agradável.", pro_tips: ["Perfeita para criar um look autêntico e menos 'posado'.", "Use para contar uma história e criar uma conexão emocional."] } },
    { name: "Hasselblad X2D 100C (Cores Naturais)", short_info: "Cores realistas e tons de pele perfeitos.", keywords: ["hasselblad x2d 100c", "medium format", "hasselblad natural colour solution", "true-to-life color", "perfect skin tones", "high-end editorial portrait"], icon: CameraIcon, technical_details: { title: "Hasselblad X2D 100C: A Ciência da Cor", description: "Esta opção é lendária por sua ciência de cores. A 'Hasselblad Natural Colour Solution' é projetada para produzir tons de pele incrivelmente precisos e belíssimos, tornando-a ideal para retratos de alta qualidade.", pro_tips: ["A melhor escolha para quando a precisão do tom de pele é a prioridade número um.", "Cria uma qualidade tridimensional que faz o retratado saltar da imagem."] } },
    { name: "Fujifilm X-T4 (Look de Filme/Analógico)", short_info: "Look cinematográfico para retratos artísticos.", keywords: ["fujifilm x-t4", "film look", "analog mood", "cinematic portrait", "moody", "artistic"], icon: CameraIcon, technical_details: { title: "Fujifilm: A Alma Analógica", description: "Famosa por suas simulações de filme, esta opção oferece cores com uma qualidade quase analógica. É perfeita para criar uma atmosfera 'moody' e artística, com tons suaves, ideal para retratos conceituais ou com um toque vintage.", pro_tips: ["Cria um look único que se destaca da fotografia de retrato tradicional.", "Excelente para retratos com uma forte identidade visual e narrativa."] } },
];
const PEOPLE_DEPTHS_OF_FIELD: Option[] = [
    { name: "Foco Seletivo (f/2.8)", short_info: "Destaca a pessoa, desfocando o fundo.", keywords: ["selective focus", "shallow dof", "subject focus", "detail isolation", "aperture f/2.8", "bokeh"], icon: SelectiveFocusIcon, technical_details: { title: "Foco Seletivo (f/2.8): O Destaque Artístico", description: "Usa uma profundidade de campo rasa (abertura f/2.8) para focar na pessoa, deixando o fundo em um desfoque suave e artístico (bokeh). É o padrão para retratos.", pro_tips: ["Cria imagens de alto impacto para ensaios e redes sociais.", "Ideal para destacar o sujeito sem a distração do ambiente."] } },
    { name: "Bokeh Suave (f/4)", short_info: "Look suave e natural, bom para lifestyle.", keywords: ["soft focus", "dreamy look", "ethereal portrait", "lifestyle", "aperture f/4", "natural bokeh background"], icon: ShallowDofIcon, technical_details: { title: "Bokeh Suave (f/4): O Toque Delicado", description: "Um desfoque de fundo suave (abertura f/4) que cria uma atmosfera delicada e natural. Mantém o contexto do ambiente visível, mas sem distrair.", pro_tips: ["Perfeito para retratos com uma estética mais orgânica e suave.", "Funciona bem com iluminação difusa para um look ainda mais delicado."] } },
    { name: "Foco Equilibrado (f/8)", short_info: "Equilíbrio entre foco na pessoa e no cenário.", keywords: ["medium depth of field", "f/8", "f/11", "balanced focus", "storytelling", "environmental portrait"], icon: MediumDofIcon, technical_details: { title: "Foco Equilibrado (f/8): O Equilíbrio Narrativo", description: "Um meio-termo (abertura f/8) que mantém a pessoa em foco nítido, mas permite que o fundo seja reconhecível e contextual. Ideal para contar uma história.", pro_tips: ["Excelente para retratos ambientais onde o local é importante.", "Oferece um look mais natural e documental."] } },
    { name: "Bokeh Extremo (Ultra Raso f/1.2)", short_info: "Desfoque máximo para um look etéreo.", keywords: ["ultra shallow dof", "dreamy bokeh", "ethereal portrait", "f/1.2 prime lens", "artistic blur"], icon: UltraShallowDofIcon, technical_details: { title: "Profundidade Ultra Rasa (f/1.2)", description: "Leva o 'fundo desfocado' a um novo nível, simulando lentes com aberturas extremas (f/1.2). Apenas os olhos do sujeito podem ficar em foco, enquanto o fundo se dissolve em um 'bokeh' suave e cremoso.", pro_tips: ["Ideal para um look sonhador, etéreo e de alta classe.", "Cria uma separação dramática entre o sujeito e o fundo."] } },
];
const PEOPLE_LIGHTING_STYLES: Option[] = [
    { name: "Luz de Estúdio (Softbox Triplo)", short_info: "Iluminação limpa, padrão para headshots.", keywords: ["three-point lighting", "clean portrait lighting", "studio shot", "no harsh reflections", "corporate headshot"], icon: StudioLightIcon, technical_details: { title: "Luz de Estúdio (Softbox Triplo): O Padrão Corporativo", description: "A configuração clássica para retratos de estúdio. Usa três fontes de luz suave (softboxes) para iluminar o sujeito de maneira uniforme, eliminando sombras fortes e criando um look profissional.", pro_tips: ["Essencial para retratos corporativos e headshots.", "Cria um look limpo, ideal para fundos brancos ou de cor sólida."] } },
    { name: "Luz Dramática (Estilo Rembrandt)", short_info: "Luz clássica com sombras suaves e profundas.", keywords: ["dramatic lighting", "rembrandt triangle", "soft shadows", "cinematic portrait", "chiaroscuro"], icon: LowKeyIcon, technical_details: { title: "Luz Dramática (Estilo Rembrandt): Drama e Sofisticação", description: "Uma técnica de iluminação clássica que cria um pequeno triângulo de luz no lado sombreado do rosto. É conhecida por seu look dramático, mas suave, que adiciona profundidade e um toque cinematográfico.", pro_tips: ["Excelente para criar uma atmosfera 'moody' e sofisticada.", "Funciona bem com fundos escuros para aumentar o drama."] } },
    { name: "Luz de Fim de Tarde (Golden Hour)", short_info: "Luz quente e suave para um look de lifestyle.", keywords: ["warm glow", "golden hour light", "sunset look", "lifestyle portrait", "soft light"], icon: GoldenHourIcon, technical_details: { title: "Luz de Fim de Tarde (Golden Hour): Calidez e Lifestyle", description: "Simula a luz quente, suave e dourada do pôr do sol. Cria uma atmosfera calorosa, orgânica e convidativa, perfeita para fotos de estilo de vida e ensaios externos.", pro_tips: ["Funciona bem em cenários naturais, como praias ou campos.", "Realça os tons de pele e cria um brilho suave no cabelo."] } },
    { name: "Luz de Janela (Natural)", short_info: "Luz suave para um estilo de vida orgânico.", keywords: ["natural window light", "soft diffused light", "organic feel", "lifestyle portrait shot", "daylight"], icon: NaturalWindowLightIcon, technical_details: { title: "Luz de Janela: A Beleza da Simplicidade", description: "A luz suave e difusa que entra por uma janela grande. É perfeita para criar um look de estilo de vida natural, orgânico e autêntico, mostrando a pessoa em um ambiente real.", pro_tips: ["Funciona melhor em dias nublados para uma luz ainda mais suave.", "Posicione a pessoa perto da janela para aproveitar ao máximo a luz e criar sombras suaves."] } },
    { name: "Luz de Neon (Urbano e Colorido)", short_info: "Cores vibrantes para um look urbano.", keywords: ["neon light", "colorful gels", "urban glow", "cyberpunk portrait", "nightlife style"], icon: NeonLightIcon, technical_details: { title: "Luz de Neon: O Brilho Urbano", description: "Usa luzes de neon ou géis coloridos para criar um look urbano, noturno e vibrante. Ideal para retratos modernos, campanhas de moda com tema noturno e para criar um visual que se destaca nas redes sociais.", pro_tips: ["Combine cores complementares para um efeito visualmente impactante.", "Abrace os reflexos coloridos na pele como parte da estética."] } },
];
const PEOPLE_CAMERA_ANGLES: Option[] = [
    { name: "Frontal (Nível do Olhar)", short_info: "Mostra o retratado de frente, ideal para headshots.", keywords: ["eye-level shot", "head-on view", "direct perspective", "corporate headshot"], icon: EyeLevelAngleIcon, technical_details: { title: "Frontal (Nível do Olhar): A Visão Direta", description: "O ângulo clássico para retratos, mostrando a pessoa de frente. Cria uma conexão direta com o espectador, sendo ideal para fotos corporativas e headshots.", pro_tips: ["Peça para a pessoa inclinar a cabeça ligeiramente para adicionar dinamismo.", "O foco deve estar sempre nos olhos."] } },
    { name: "Ângulo 45° (Hero Shot)", short_info: "O ângulo versátil e natural para retratos.", keywords: ["hero shot", "three-quarter view", "natural perspective", "lifestyle portrait", "depth perception"], icon: FortyFiveDegreeAngleIcon, technical_details: { title: "Ângulo 45° (Hero Shot): O Padrão Ouro", description: "O ângulo mais comum e eficaz para retratos. Mostra o rosto e o corpo em um ângulo ligeiro, oferecendo uma visão tridimensional que revela profundidade e forma. É a visão mais natural.", pro_tips: ["A escolha ideal para a foto principal de um ensaio.", "Funciona para quase todos os tipos de retratos e estilos."] } },
    { name: "De Baixo (Imponente)", short_info: "Faz a pessoa parecer mais alta e poderosa.", keywords: ["low angle shot", "imposing look", "powerful pose", "heroic perspective", "editorial"], icon: LowAngleIcon, technical_details: { title: "De Baixo (Imponente): A Perspectiva Heroica", description: "A câmera é posicionada ligeiramente abaixo da pessoa, olhando para cima. Isso cria uma perspectiva que a torna maior, mais grandiosa e poderosa. Transmite uma sensação de poder e confiança.", pro_tips: ["Excelente para retratos corporativos de CEO's e editoriais de moda.", "Alonga o corpo, criando uma silhueta elegante."] } },
    { name: "Super Close-up (Macro)", short_info: "Foco em detalhes como olhos e expressão.", keywords: ["macro detail", "close-up shot", "eye focus", "expression detail", "beauty shot"], icon: ExtremeCloseUpAngleIcon, technical_details: { title: "Super Close-up (Macro): A Janela da Alma", description: "Um enquadramento super fechado que revela a emoção e os detalhes do rosto - o brilho nos olhos, a textura da pele ou um sorriso sutil. É sobre capturar a essência da pessoa.", pro_tips: ["Requer iluminação precisa e foco perfeito nos olhos.", "Revela detalhes que criam uma conexão íntima com o espectador."] } },
];
const PEOPLE_PRESETS: StudioPreset[] = [
    { name: "Retrato (Corporativo)", description: "Retrato profissional para uso corporativo.", icon: PeopleIcon, preset: { cameraName: 'Nikon Z7 II 85mm f/1.8 (Fundo Comprimido)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'Frontal (Nível do Olhar)', stylePlaceholder: 'Headshot profissional de uma pessoa em trajes de negócios, com um fundo de escritório moderno e desfocado.' }, examples: ["headshot", "corporate portrait", "professional", "business"] },
    { name: "Lifestyle (Cotidiano)", description: "Cena casual mostrando pessoas em atividades.", icon: PeopleIcon, preset: { cameraName: 'Sony A7 IV 35mm f/1.4 (Estilo Lifestyle)', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz de Janela (Natural)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Pessoa sorrindo enquanto toma café em uma cafeteria bem iluminada, com a luz da janela iluminando a cena.' }, examples: ["lifestyle", "candid", "portrait", "coffee shop", "natural light"] },
    { name: "Retrato (Artístico)", description: "Retrato expressivo com iluminação dramática.", icon: PeopleIcon, preset: { cameraName: 'Fujifilm X-T4 (Look de Filme/Analógico)', depthOfFieldName: 'Bokeh Extremo (Ultra Raso f/1.2)', lightingName: 'Luz Dramática (Estilo Rembrandt)', angle: 'Super Close-up (Macro)', stylePlaceholder: 'Close-up de um rosto com expressão intensa, iluminação dramática de um lado, fundo escuro, criando um efeito chiaroscuro, look cinematográfico.' }, examples: ["fine art portrait", "dramatic portrait", "chiaroscuro", "low key", "expressive"] },
    { name: "Esportes (Ação)", description: "Capture atletas em movimento com impacto.", icon: PeopleIcon, preset: { cameraName: 'Nikon Z7 II 85mm f/1.8 (Fundo Comprimido)', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz Dura (Brilho Intenso)', angle: 'De Baixo (Imponente)', stylePlaceholder: 'Jogador de futebol no meio de um chute, com gotas de suor congeladas no ar, estádio desfocado ao fundo, iluminação de alto contraste.' }, examples: ["sports photography", "action shot", "athlete", "dynamic", "high speed"] },
    { name: "Família (Ensaio Externo)", description: "Cena natural e afetuosa de uma família.", icon: PeopleIcon, preset: { cameraName: 'Canon EOS R5 50mm f/1.8 (Look Natural de Lifestyle)', depthOfFieldName: 'Bokeh Suave (f/4)', lightingName: 'Luz de Fim de Tarde (Golden Hour)', angle: 'Frontal (Nível do Olhar)', stylePlaceholder: 'Família rindo e caminhando de mãos dadas em um parque durante o pôr do sol, com a luz dourada criando um brilho suave ao redor deles.' }, examples: ["family portrait", "golden hour", "lifestyle", "candid", "outdoors"] },
    { name: "Retrato (Rua/Urbano)", description: "Retrato casual em um ambiente urbano.", icon: PeopleIcon, preset: { cameraName: 'Sony A7 IV 35mm f/1.4 (Estilo Lifestyle)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz de Neon (Urbano e Colorido)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Pessoa encostada em uma parede com grafite, em uma rua noturna com luzes de neon coloridas refletindo no rosto, look moderno e urbano.' }, examples: ["street portrait", "urban", "neon lights", "candid", "environmental portrait"] },
    { name: "Ensaio de Casal (Romântico)", description: "Cena romântica e íntima para ensaios de casais.", icon: PeopleIcon, preset: { cameraName: 'Canon EOS R5 50mm f/1.8 (Look Natural de Lifestyle)', depthOfFieldName: 'Bokeh Suave (f/4)', lightingName: 'Luz de Fim de Tarde (Golden Hour)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Casal de mãos dadas, sorrindo um para o outro em um campo florido durante o pôr do sol, com a luz dourada criando um halo suave ao redor deles.' }, examples: ["ensaio de casal", "pre-wedding", "romântico", "golden hour", "afeto"] },
    { name: "Retrato de Beleza (Close-up)", description: "Close-up focado em pele e maquiagem com perfeição.", icon: PeopleIcon, preset: { cameraName: 'Hasselblad X2D 100C (Cores Naturais)', depthOfFieldName: 'Bokeh Extremo (Ultra Raso f/1.2)', lightingName: 'Luz de Estúdio (Softbox Triplo)', angle: 'Super Close-up (Macro)', stylePlaceholder: 'Close-up extremo do rosto de uma modelo com maquiagem impecável, pele brilhante, com foco nos olhos, fundo de cor sólida e suave.' }, examples: ["beauty shot", "maquiagem", "pele", "close-up", "editorial de beleza"] },
    { name: "Ensaio de Gestante (Delicado)", description: "Cena suave e etérea para celebrar a maternidade.", icon: PeopleIcon, preset: { cameraName: 'Hasselblad X2D 100C (Cores Naturais)', depthOfFieldName: 'Bokeh Suave (f/4)', lightingName: 'Luz de Janela (Natural)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Mulher grávida em um vestido fluido, em um quarto bem iluminado com cortinas brancas esvoaçantes, segurando a barriga com um sorriso sereno.' }, examples: ["ensaio de gestante", "maternidade", "delicado", "luz natural", "vida"] },
    { name: "Retrato P&B (Clássico)", description: "Retrato atemporal em preto e branco, focado em expressão.", icon: PeopleIcon, preset: { cameraName: 'Fujifilm X-T4 (Look de Filme/Analógico)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz Dramática (Estilo Rembrandt)', angle: 'Frontal (Nível do Olhar)', stylePlaceholder: 'Retrato em preto e branco de alto contraste de um rosto com expressão pensativa, luz dramática vindo de um lado, fundo escuro e texturizado.' }, examples: ["preto e branco", "retrato P&B", "clássico", "atemporal", "monocromático"] },
    { name: "Retrato de Viagem (Aventura)", description: "Capture o espírito da aventura em paisagens incríveis.", icon: PeopleIcon, preset: { cameraName: 'Sony A7 IV 35mm f/1.4 (Estilo Lifestyle)', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz de Fim de Tarde (Golden Hour)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Viajante com mochila em pé no topo de uma montanha, olhando para o vale ao pôr do sol, com uma sensação de admiração e liberdade.' }, examples: ["viagem", "aventura", "paisagem", "mochileiro", "explorador"] },
    { name: "Músico/Artista (Promocional)", description: "Cena 'moody' e criativa para fotos promocionais de artistas.", icon: PeopleIcon, preset: { cameraName: 'Fujifilm X-T4 (Look de Filme/Analógico)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz de Neon (Urbano e Colorido)', angle: 'De Baixo (Imponente)', stylePlaceholder: 'Músico segurando uma guitarra em um beco urbano à noite, com luzes de neon refletindo no instrumento e no chão molhado.' }, examples: ["músico", "artista", "foto promocional", "banda", "urbano noturno"] },
    { name: "Crianças (Espontâneo)", description: "Capture a alegria e a energia natural das crianças.", icon: PeopleIcon, preset: { cameraName: 'Canon EOS R5 50mm f/1.8 (Look Natural de Lifestyle)', depthOfFieldName: 'Bokeh Suave (f/4)', lightingName: 'Luz de Fim de Tarde (Golden Hour)', angle: 'Frontal (Nível do Olhar)', stylePlaceholder: 'Criança rindo enquanto corre em um gramado durante o verão, com bolhas de sabão flutuando ao redor, luz do sol suave de fim de tarde.' }, examples: ["crianças", "infantil", "brincadeira", "espontâneo", "alegria"] },
    { name: "Ensaio Sensual (Boudoir)", description: "Cena íntima e elegante com foco em sensualidade e confiança.", icon: PeopleIcon, preset: { cameraName: 'Fujifilm X-T4 (Look de Filme/Analógico)', depthOfFieldName: 'Bokeh Extremo (Ultra Raso f/1.2)', lightingName: 'Luz de Janela (Natural)', angle: 'Ângulo 45° (Hero Shot)', stylePlaceholder: 'Mulher em lingerie de seda em um quarto de hotel de luxo, com luz suave da janela criando sombras delicadas, lençóis de cetim na cama.' }, examples: ["boudoir", "sensual", "íntimo", "elegante", "confiança"] },
    { name: "Retrato de Escritor (Intelectual)", description: "Retrato clássico e pensativo, ideal para autores e acadêmicos.", icon: PeopleIcon, preset: { cameraName: 'Nikon Z7 II 85mm f/1.8 (Fundo Comprimido)', depthOfFieldName: 'Foco Seletivo (f/2.8)', lightingName: 'Luz de Janela (Natural)', angle: 'Frontal (Nível do Olhar)', stylePlaceholder: 'Escritor sentado em uma poltrona de couro em uma biblioteca ou escritório em casa, com estantes de livros desfocadas ao fundo, luz suave de janela.' }, examples: ["autor", "escritor", "intelectual", "retrato profissional", "biblioteca"] },
    { name: "Cultura Pop/Cosplay (Vibrante)", description: "Cena dinâmica e colorida para retratos de cosplay e cultura pop.", icon: PeopleIcon, preset: { cameraName: 'Sony A7 IV 35mm f/1.4 (Estilo Lifestyle)', depthOfFieldName: 'Foco Equilibrado (f/8)', lightingName: 'Luz de Neon (Urbano e Colorido)', angle: 'De Baixo (Imponente)', stylePlaceholder: 'Pessoa em um traje de cosplay detalhado de super-herói, posando em um beco com luzes de neon, criando uma atmosfera de história em quadrinhos.' }, examples: ["cosplay", "cultura pop", "gamer", "fantasia", "super-herói"] }
];

export const peopleStudioConfig = {
    id: 'people' as const,
    name: "Estúdio de Pessoas AI",
    specialty: "fotografia de pessoas e retratos",
    presets: PEOPLE_PRESETS,
    cameras: PEOPLE_CAMERAS,
    angles: PEOPLE_CAMERA_ANGLES,
    depthsOfField: PEOPLE_DEPTHS_OF_FIELD,
    lightingStyles: PEOPLE_LIGHTING_STYLES,
};